/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Все сообщения обратной связи всех пользователей (только для администратора) */
        get: operations["AdminUsers_listFeedback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список всех пользователей (только для администратора) */
        get: operations["AdminUsers_listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Удалить пользователя вместе со всеми данными (только для администратора) */
        delete: operations["AdminUsers_deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth_forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cba/common-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Общий банк типовых пунктов плюсов/минусов */
        get: operations["Cba_listCommonItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cba/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description История записей текущего пользователя, новые сверху */
        get: operations["Cba_listEntries"];
        put?: never;
        post: operations["Cba_createEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cba/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["Cba_deleteEntry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cba/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Библиотека разобранных обучающих примеров */
        get: operations["Cba_listExamples"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creature": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить текущее состояние существа */
        get: operations["Creature_getState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creature/check-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Ежедневная отметка — восстанавливает энергию, начисляет опыт, обновляет streak */
        post: operations["Creature_checkIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creature/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description История выполненных практик за последние N дней (по умолчанию 30) */
        get: operations["Creature_getCompletions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creature/exercise/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Завершить дыхательное упражнение, обновить уровень спокойствия, начислить опыт */
        post: operations["Creature_completeExercise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creature/pet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Активировать питомца и/или задать имя */
        patch: operations["Creature_setPet"];
        trace?: never;
    };
    "/creature/pets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить коллекцию питомцев пользователя */
        get: operations["Creature_getPets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creature/reward": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Начислить опыт за выполнение практики (gratitude, sleepHygiene, distortions, cba) */
        post: operations["Creature_reward"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/digest/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Недельный дайджест активности пользователя */
        get: operations["Digest_getWeekly"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Entries_list"];
        put?: never;
        post: operations["Entries_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Entries_get"];
        put?: never;
        post?: never;
        delete: operations["Entries_delete"];
        options?: never;
        head?: never;
        patch: operations["Entries_update"];
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FeedbackApi_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FeedbackApi_listMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding-stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OnboardingStories_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Parameters_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Reports_list"];
        put?: never;
        post: operations["Reports_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Reports_get"];
        put?: never;
        post?: never;
        delete: operations["Reports_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Reports_download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TestResults_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test-results/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TestResults_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Tests_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Tests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tests/{id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Tests_submitResult"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Users_getMe"];
        put?: never;
        post?: never;
        delete: operations["Users_deleteMe"];
        options?: never;
        head?: never;
        patch: operations["Users_updateMe"];
        trace?: never;
    };
    "/users/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Users_getPreferences"];
        put: operations["Users_savePreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Запись обратной связи для админ-панели (все пользователи) */
        AdminFeedback: {
            id: string;
            message: string;
            /** Format: date-time */
            createdAt: string;
            user: {
                email: string;
                name?: string;
            };
        };
        /** @description Запись списка пользователей для админ-панели */
        AdminUser: {
            id: string;
            email: string;
            name?: string;
            role: string;
            /** Format: date-time */
            createdAt: string;
            emailVerified: boolean;
            ageConfirmed: boolean;
            /** Format: int32 */
            entriesCount: number;
            /** Format: int32 */
            testResultsCount: number;
            /** Format: int32 */
            breathingSessionsCount: number;
            /** Format: int32 */
            cbaEntriesCount: number;
        };
        AuthResponse: {
            accessToken: string;
            user: components["schemas"]["User"];
        };
        /** @description Результат завершённого дыхательного упражнения */
        BreathingCompleteRequest: {
            /**
             * Format: int32
             * @description Длительность упражнения в секундах
             */
            duration: number;
        };
        /** @description Сессия дыхательного упражнения */
        BreathingSession: {
            id: string;
            userId: string;
            /**
             * Format: int32
             * @description Длительность упражнения в секундах
             */
            duration: number;
            /**
             * Format: int32
             * @description Уровень спокойствия до упражнения
             */
            initialCalmness: number;
            /**
             * Format: int32
             * @description Уровень спокойствия после упражнения
             */
            finalCalmness: number;
            /** Format: date-time */
            completedAt: string;
        };
        /** @description Типовой пункт из общего банка подсказок для заполнения формы CBA */
        CbaCommonItem: {
            id: string;
            itemType: components["schemas"]["CbaItemType"];
            itemText: string;
        };
        /** @description Запись пользователя в технике "анализ издержек и выгод": мысль + плюсы/минусы + соотношение (в сумме 100) */
        CbaEntry: {
            id: string;
            userId: string;
            thoughtText: string;
            /** Format: int32 */
            prosWeight: number;
            /** Format: int32 */
            consWeight: number;
            /** Format: date-time */
            createdAt: string;
            items: components["schemas"]["CbaEntryItem"][];
        };
        CbaEntryCreate: {
            thoughtText: string;
            /** Format: int32 */
            prosWeight: number;
            /** Format: int32 */
            consWeight: number;
            items: components["schemas"]["CbaEntryItemInput"][];
        };
        CbaEntryItem: {
            id: string;
            itemType: components["schemas"]["CbaItemType"];
            itemText: string;
        };
        CbaEntryItemInput: {
            itemType: components["schemas"]["CbaItemType"];
            itemText: string;
        };
        /** @description Разобранный обучающий пример техники "анализ издержек и выгод" на вымышленном персонаже */
        CbaExample: {
            id: string;
            persona: string;
            thoughtText: string;
            /** Format: int32 */
            prosWeight: number;
            /** Format: int32 */
            consWeight: number;
            /** Format: int32 */
            order: number;
            items: components["schemas"]["CbaExampleItem"][];
            distortions: components["schemas"]["CbaExampleDistortion"][];
        };
        /** @description Когнитивное искажение, отмеченное в мысли обучающего примера (ключ из библиотеки искажений) */
        CbaExampleDistortion: {
            id: string;
            exampleId: string;
            distortionKey: string;
        };
        CbaExampleItem: {
            id: string;
            itemType: components["schemas"]["CbaItemType"];
            itemText: string;
        };
        /**
         * @description Тип пункта: довод "за" веру в мысль (advantage) или "против" (disadvantage)
         * @enum {string}
         */
        CbaItemType: "advantage" | "disadvantage";
        /** @description Результат ежедневного чекина */
        CheckInResponse: {
            state: components["schemas"]["CreatureState"];
            /** @description Был ли достигнут новый уровень */
            leveledUp: boolean;
        };
        /** @description Текущее состояние существа пользователя */
        CreatureState: {
            id: string;
            userId: string;
            /**
             * Format: int32
             * @description Уровень спокойствия: 0 — крайне тревожно, 100 — полное спокойствие
             */
            calmness: number;
            /**
             * Format: int32
             * @description Энергия существа: 0 (истощён) — 100 (полон сил)
             */
            energy: number;
            /**
             * Format: int32
             * @description Уровень существа
             */
            level: number;
            /**
             * Format: int32
             * @description Опыт на текущем уровне
             */
            experience: number;
            /**
             * Format: int32
             * @description Текущая серия ежедневных отметок
             */
            streak: number;
            /**
             * Format: date-time
             * @description Дата последнего ежедневного чекина
             */
            lastCheckInAt?: string;
            /**
             * Format: date-time
             * @description Дата последнего дыхательного упражнения
             */
            lastExerciseAt?: string;
            /** @description Текущий выбранный тип питомца */
            petType?: string;
            /** @description Открытые типы питомцев */
            unlockedPetTypes?: string[];
            /** @description Имя питомца, заданное пользователем */
            petName?: string;
            /** @description Активный титул */
            activeTitle?: string;
            /** @description Открытые титулы */
            unlockedTitles?: string[];
            /** @description Активный скин */
            activeSkin?: string;
            /** @description Открытые скины */
            unlockedSkins?: string[];
        };
        /** @description Запись значения параметра в конкретный момент времени */
        Entry: {
            id: string;
            userId: string;
            parameterId: string;
            /** Format: double */
            value: number;
            note?: string;
            /** Format: date-time */
            createdAt: string;
        };
        EntryCreate: {
            parameterId: string;
            /** Format: double */
            value: number;
            note?: string;
        };
        EntryUpdate: {
            /** Format: double */
            value?: number;
            note?: string;
        };
        Error: {
            code: string;
            message: string;
        };
        /** @description Обратная связь от пользователя (сбор ОС) */
        Feedback: {
            id: string;
            userId: string;
            message: string;
            /** Format: date-time */
            createdAt: string;
        };
        FeedbackCreate: {
            message: string;
        };
        ForgotPasswordRequest: {
            email: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        /** @description Обучающая история для онбординга новых пользователей после регистрации */
        OnboardingStory: {
            id: string;
            title: string;
            content: string;
            /** Format: int32 */
            order: number;
        };
        /** @description Отслеживаемый параметр ментального здоровья (тревожность, сон, настроение и т.д.). Справочник, задаётся разработчиком/экспертом, не пользователем. */
        Parameter: {
            id: string;
            name: string;
            description?: string;
            unit?: string;
        };
        /** @description Коллекция питомцев пользователя */
        PetCollection: {
            unlockedPetTypes: string[];
            activePetType: string;
            petName: string;
        };
        /** @description Тело обновления питомца */
        PetUpdateRequest: {
            /** @description Тип питомца для активации */
            petType?: string;
            /** @description Новое имя питомца (пустая строка очищает) */
            petName?: string;
        };
        /** @description Запись о выполненной практике и полученном опыте */
        PracticeCompletion: {
            source: string;
            /** Format: int32 */
            xpAwarded: number;
            /** Format: date-time */
            createdAt: string;
        };
        RefreshResponse: {
            accessToken: string;
        };
        /** @description Отчёт для выгрузки статистики врачу (PDF/CSV), без участия врача в самом приложении */
        Report: {
            id: string;
            userId: string;
            format: components["schemas"]["ReportFormat"];
            status: components["schemas"]["ReportStatus"];
            /** Format: date-time */
            periodFrom: string;
            /** Format: date-time */
            periodTo: string;
            /** Format: date-time */
            createdAt: string;
            downloadUrl?: string;
        };
        ReportCreate: {
            format: components["schemas"]["ReportFormat"];
            /** Format: date-time */
            periodFrom: string;
            /** Format: date-time */
            periodTo: string;
        };
        /** @enum {string} */
        ReportFormat: "pdf" | "csv";
        /**
         * @description Статус генерации отчёта
         * @enum {string}
         */
        ReportStatus: "pending" | "ready" | "failed";
        ResetPasswordRequest: {
            token: string;
            password: string;
        };
        ResetPasswordResponse: {
            accessToken: string;
            message: string;
        };
        /** @description Запрос на награду за практику */
        RewardRequest: {
            source: string;
        };
        /** @description Результат награды за практику */
        RewardResponse: {
            state: components["schemas"]["CreatureState"];
            /** @description Был ли достигнут новый уровень */
            leveledUp: boolean;
        };
        /** @description Психологический тест, построенный на справочниках/книгах по психологии. Шаблон: вопросы + правила подсчёта баллов. */
        Test: {
            id: string;
            title: string;
            description?: string;
            active: boolean;
            questions: components["schemas"]["TestQuestion"][];
        };
        TestAnswer: {
            questionId: string;
            optionId: string;
        };
        TestDigest: {
            id: string;
            title: string;
            description?: string;
            active: boolean;
        };
        TestQuestion: {
            id: string;
            text: string;
            options: components["schemas"]["TestQuestionOption"][];
        };
        TestQuestionOption: {
            id: string;
            text: string;
            /** Format: int32 */
            score: number;
        };
        /** @description Конкретная попытка прохождения теста пользователем: ответы, посчитанный балл и рекомендация */
        TestResult: {
            id: string;
            testId: string;
            userId: string;
            /** Format: int32 */
            score: number;
            interpretation: string;
            recommendation: string;
            /** @description Дополнительные флаги/профили (например, per-distortion scores для теста когнитивных искажений) */
            flags?: unknown;
            /** Format: date-time */
            completedAt: string;
        };
        TestResultDigest: {
            testId: string;
            title: string;
            /** Format: int32 */
            score: number;
            interpretation: string;
        };
        TestResultSubmit: {
            answers: components["schemas"]["TestAnswer"][];
        };
        /** @description Пользователь приложения */
        User: {
            id: string;
            email: string;
            name?: string;
            role: string;
            /** Format: date-time */
            createdAt: string;
        };
        UserCreate: {
            email: string;
            password: string;
            name?: string;
        };
        /** @description Настройки и предпочтения пользователя */
        UserPreference: {
            goals: string[];
            experienceLevel: string;
            dailyReminder: boolean;
            reminderTime?: string;
            onboardingDone: boolean;
        };
        UserPreferenceUpdate: {
            goals?: string[];
            experienceLevel?: string;
            dailyReminder?: boolean;
            reminderTime?: string;
            onboardingDone?: boolean;
        };
        UserUpdate: {
            name?: string;
        };
        /** @description Результаты тестирования за неделю */
        WeeklyDigest: {
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate: string;
            /** Format: int32 */
            totalEntries: number;
            averages: unknown;
            /** Format: int32 */
            checkInDays: number;
            testsTaken: components["schemas"]["TestResultDigest"][];
            practicesCompleted: unknown;
            /** Format: int32 */
            creatureXpGained: number;
            /** Format: int32 */
            creatureLevel: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdminUsers_listFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminFeedback"][];
                };
            };
        };
    };
    AdminUsers_listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"][];
                };
            };
        };
    };
    AdminUsers_deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Auth_forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    Auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Auth_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
        };
    };
    Auth_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    Auth_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetPasswordResponse"];
                };
            };
        };
    };
    Cba_listCommonItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CbaCommonItem"][];
                };
            };
        };
    };
    Cba_listEntries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CbaEntry"][];
                };
            };
        };
    };
    Cba_createEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CbaEntryCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CbaEntry"];
                };
            };
        };
    };
    Cba_deleteEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Cba_listExamples: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CbaExample"][];
                };
            };
        };
    };
    Creature_getState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatureState"];
                };
            };
        };
    };
    Creature_checkIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInResponse"];
                };
            };
        };
    };
    Creature_getCompletions: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeCompletion"][];
                };
            };
        };
    };
    Creature_completeExercise: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BreathingCompleteRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInResponse"];
                };
            };
        };
    };
    Creature_setPet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PetUpdateRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PetCollection"];
                };
            };
        };
    };
    Creature_getPets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PetCollection"];
                };
            };
        };
    };
    Creature_reward: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RewardRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RewardResponse"];
                };
            };
        };
    };
    Digest_getWeekly: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyDigest"];
                };
            };
        };
    };
    Entries_list: {
        parameters: {
            query?: {
                parameterId?: string;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"][];
                };
            };
        };
    };
    Entries_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
        };
    };
    Entries_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
        };
    };
    Entries_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Entries_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
        };
    };
    FeedbackApi_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"];
                };
            };
        };
    };
    FeedbackApi_listMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"][];
                };
            };
        };
    };
    OnboardingStories_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingStory"][];
                };
            };
        };
    };
    Parameters_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Parameter"][];
                };
            };
        };
    };
    Reports_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"][];
                };
            };
        };
    };
    Reports_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
        };
    };
    Reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
        };
    };
    Reports_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Reports_download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    TestResults_list: {
        parameters: {
            query?: {
                testId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestResult"][];
                };
            };
        };
    };
    TestResults_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestResult"];
                };
            };
        };
    };
    Tests_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestDigest"][];
                };
            };
        };
    };
    Tests_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Test"];
                };
            };
        };
    };
    Tests_submitResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestResultSubmit"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestResult"];
                };
            };
        };
    };
    Users_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    Users_deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Users_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    Users_getPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreference"];
                };
            };
        };
    };
    Users_savePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPreferenceUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreference"];
                };
            };
        };
    };
}
