/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Все сообщения обратной связи всех пользователей (только для администратора) */
        get: operations["AdminUsers_listFeedback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список всех пользователей (только для администратора) */
        get: operations["AdminUsers_listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Удалить пользователя вместе со всеми данными (только для администратора) */
        delete: operations["AdminUsers_deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/tier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Вручную выставить тариф пользователя (биллинга нет, только для администратора) */
        patch: operations["AdminUsers_updateUserTier"];
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth_forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Отдать recovery-материал (wrappedKey/salt) по токену сброса пароля */
        post: operations["Auth_resetInfo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/set-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Сохранить E2E-ключи для legacy-учётки (только если ключей ещё нет); требователен к авторизации */
        post: operations["Auth_setKeys"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cba/common-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Общий банк типовых пунктов плюсов/минусов */
        get: operations["Cba_listCommonItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cba/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description История записей текущего пользователя, новые сверху */
        get: operations["Cba_listEntries"];
        put?: never;
        post: operations["Cba_createEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cba/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["Cba_deleteEntry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cba/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Библиотека разобранных обучающих примеров */
        get: operations["Cba_listExamples"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/message-of-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Пожелание дня (morning/day/evening) для текущего пользователя */
        get: operations["Content_messageOfDay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список пожеланий (только контент-менеджер/админ) */
        get: operations["Content_listMessages"];
        put?: never;
        /** @description Создать пожелание (только контент-менеджер/админ) */
        post: operations["Content_createMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/messages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Удалить пожелание (только контент-менеджер/админ) */
        delete: operations["Content_deleteMessage"];
        options?: never;
        head?: never;
        /** @description Обновить пожелание (только контент-менеджер/админ) */
        patch: operations["Content_updateMessage"];
        trace?: never;
    };
    "/creature": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить текущее состояние существа */
        get: operations["Creature_getState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creature/adventure/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Забрать награду за «прогулку» компаньона (доступно после adventureReturnAt) */
        post: operations["Creature_claimAdventure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creature/check-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Ежедневная отметка — восстанавливает энергию, начисляет опыт, обновляет streak */
        post: operations["Creature_checkIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creature/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description История выполненных практик за последние N дней (по умолчанию 30) */
        get: operations["Creature_getCompletions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creature/exercise/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Завершить дыхательное упражнение, обновить уровень спокойствия, начислить опыт */
        post: operations["Creature_completeExercise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creature/pet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Погладить компаньона: цикл 1-2-3 с XP и скрытыми бонусами (утро/вечер/комбо/возвращение/эмпатия) */
        post: operations["Creature_pet"];
        delete?: never;
        options?: never;
        head?: never;
        /** @description Активировать питомца и/или задать имя */
        patch: operations["Creature_setPet"];
        trace?: never;
    };
    "/creature/pets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить коллекцию питомцев пользователя */
        get: operations["Creature_getPets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creature/reward": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Начислить опыт за выполнение практики (gratitude, sleepHygiene, distortions, cba, thoughtBattle, responsibilityPie, decatastrophizing) */
        post: operations["Creature_reward"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creature/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Недельный календарь практик (Пн–Вс): прогресс к цели, статус подарка +25 XP */
        get: operations["Creature_getWeekly"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creature/weekly/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Забрать недельный подарок +XP (одноразово на неделю, только при достигнутой цели) */
        post: operations["Creature_claimWeekly"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decatastrophizing/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description История записей текущего пользователя, новые сверху */
        get: operations["Decatastrophizing_listEntries"];
        put?: never;
        post: operations["Decatastrophizing_createEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decatastrophizing/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["Decatastrophizing_deleteEntry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emotion-lab/attempt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Смешать две эмоции: проверяет дневной лимит и доступность уровня диады. При исчерпании лимита — 403 { error: 'daily_limit_reached', limit, tier, resetsAt } */
        post: operations["EmotionLab_attempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emotion-lab/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Состояние лаборатории эмоций: открытые диады, доступный уровень, оставшиеся попытки сегодня */
        get: operations["EmotionLab_getState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Entries_list"];
        put?: never;
        post: operations["Entries_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Entries_get"];
        put?: never;
        post?: never;
        delete: operations["Entries_delete"];
        options?: never;
        head?: never;
        patch: operations["Entries_update"];
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FeedbackApi_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FeedbackApi_listMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding-stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OnboardingStories_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Parameters_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Reports_list"];
        put?: never;
        post: operations["Reports_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Reports_get"];
        put?: never;
        post?: never;
        delete: operations["Reports_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Reports_download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/responsibility-pie/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description История записей текущего пользователя, новые сверху */
        get: operations["ResponsibilityPie_listEntries"];
        put?: never;
        post: operations["ResponsibilityPie_createEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/responsibility-pie/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["ResponsibilityPie_deleteEntry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TestResults_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test-results/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TestResults_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Tests_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Tests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Users_getMe"];
        put?: never;
        post?: never;
        delete: operations["Users_deleteMe"];
        options?: never;
        head?: never;
        patch: operations["Users_updateMe"];
        trace?: never;
    };
    "/users/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Users_getPreferences"];
        put: operations["Users_savePreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Запись обратной связи для админ-панели (все пользователи) */
        AdminFeedback: {
            id: string;
            /**
             * Format: int32
             * @description Оценка приложения от 1 до 5
             */
            rating: number;
            message: string;
            /** Format: date-time */
            createdAt: string;
            user: {
                email: string;
                name?: string;
            };
        };
        /** @description Запись списка пользователей для админ-панели */
        AdminUser: {
            id: string;
            email: string;
            name?: string;
            role: string;
            /** Format: date-time */
            createdAt: string;
            emailVerified: boolean;
            ageConfirmed: boolean;
            /** @description Тариф: free | premium (выставляется вручную из админ-панели, биллинга нет) */
            subscriptionTier: string;
            /**
             * Format: date-time
             * @description Дата истечения premium-тарифа, если задана
             */
            subscriptionExpiresAt?: string;
            /** Format: int32 */
            entriesCount: number;
            /** Format: int32 */
            testResultsCount: number;
            /** Format: int32 */
            breathingSessionsCount: number;
            /** Format: int32 */
            cbaEntriesCount: number;
        };
        /** @description Результат изменения тарифа пользователя */
        AdminUserTierResult: {
            id: string;
            email: string;
            subscriptionTier: string;
            /** Format: date-time */
            subscriptionExpiresAt?: string;
        };
        /** @description Тело запроса на изменение тарифа пользователя */
        AdminUserTierUpdate: {
            /** @description free | premium */
            tier?: string;
            /**
             * Format: date-time
             * @description ISO-дата истечения premium или null — снять ограничение по сроку
             */
            expiresAt?: string | null;
        };
        AuthResponse: {
            accessToken: string;
            user: components["schemas"]["User"];
            /** @description DEK, зашифрованный ключом из пароля — нужен клиенту для разблокировки данных при логине */
            wrappedKey?: string;
            /** @description Соль для вывода KEK из пароля */
            keySalt?: string;
        };
        /** @description Результат завершённого дыхательного упражнения */
        BreathingCompleteRequest: {
            /**
             * Format: int32
             * @description Длительность упражнения в секундах
             */
            duration: number;
        };
        /** @description Сессия дыхательного упражнения */
        BreathingSession: {
            id: string;
            userId: string;
            /**
             * Format: int32
             * @description Длительность упражнения в секундах
             */
            duration: number;
            /**
             * Format: int32
             * @description Уровень спокойствия до упражнения
             */
            initialCalmness: number;
            /**
             * Format: int32
             * @description Уровень спокойствия после упражнения
             */
            finalCalmness: number;
            /** Format: date-time */
            completedAt: string;
        };
        /** @description Типовой пункт из общего банка подсказок для заполнения формы CBA */
        CbaCommonItem: {
            id: string;
            itemType: components["schemas"]["CbaItemType"];
            itemText: string;
            category: components["schemas"]["CbaItemCategory"];
            itemKey: string;
        };
        /** @description Запись пользователя в технике "анализ издержек и выгод": мысль + плюсы/минусы + соотношение (в сумме 100) */
        CbaEntry: {
            id: string;
            userId: string;
            thoughtText: string;
            /** Format: int32 */
            prosWeight: number;
            /** Format: int32 */
            consWeight: number;
            /** Format: date-time */
            createdAt: string;
            items: components["schemas"]["CbaEntryItem"][];
        };
        CbaEntryCreate: {
            thoughtText: string;
            /** Format: int32 */
            prosWeight: number;
            /** Format: int32 */
            consWeight: number;
            items: components["schemas"]["CbaEntryItemInput"][];
        };
        CbaEntryItem: {
            id: string;
            itemType: components["schemas"]["CbaItemType"];
            itemText: string;
        };
        CbaEntryItemInput: {
            itemType: components["schemas"]["CbaItemType"];
            itemText: string;
        };
        /** @description Разобранный обучающий пример техники "анализ издержек и выгод" на вымышленном персонаже */
        CbaExample: {
            id: string;
            persona: string;
            thoughtText: string;
            /** Format: int32 */
            prosWeight: number;
            /** Format: int32 */
            consWeight: number;
            /** Format: int32 */
            order: number;
            items: components["schemas"]["CbaExampleItem"][];
            distortions: components["schemas"]["CbaExampleDistortion"][];
        };
        /** @description Когнитивное искажение, отмеченное в мысли обучающего примера (ключ из библиотеки искажений) */
        CbaExampleDistortion: {
            id: string;
            exampleId: string;
            distortionKey: string;
        };
        CbaExampleItem: {
            id: string;
            itemType: components["schemas"]["CbaItemType"];
            itemText: string;
        };
        /**
         * @description Тема автоматической мысли, к которой относится подсказка
         * @enum {string}
         */
        CbaItemCategory: "anxiety" | "self-esteem" | "relationships" | "work" | "health" | "habit";
        /**
         * @description Тип пункта: довод "за" веру в мысль (advantage) или "против" (disadvantage)
         * @enum {string}
         */
        CbaItemType: "advantage" | "disadvantage";
        /** @description Результат ежедневного чекина */
        CheckInResponse: {
            state: components["schemas"]["CreatureState"];
            /** @description Был ли достигнут новый уровень */
            leveledUp: boolean;
            /** @description Пропуск дня был покрыт токеном заморозки стрика вместо сброса серии */
            streakFreezeUsed: boolean;
            /**
             * Format: int32
             * @description Сработавший comeback-тир в днях (7 / 14 / 30), если чек-ин пришёл после долгого перерыва
             */
            comebackDays?: number;
        };
        /** @description Результат получения награды за «прогулку» компаньона */
        ClaimAdventureResponse: {
            state: components["schemas"]["CreatureState"];
            /** @description Был ли достигнут новый уровень */
            leveledUp: boolean;
            /**
             * Format: int32
             * @description Сколько XP начислено
             */
            xpAwarded: number;
            /**
             * Format: int32
             * @description На сколько вырос comfort
             */
            comfortGain: number;
        };
        /** @description Результат получения недельного подарка */
        ClaimWeeklyResponse: {
            claimed: boolean;
            /**
             * Format: int32
             * @description Сколько XP начислено
             */
            xpAwarded: number;
            /** @description Был ли достигнут новый уровень */
            leveledUp: boolean;
        };
        /** @description Текущее состояние существа пользователя */
        CreatureState: {
            id: string;
            userId: string;
            /**
             * Format: int32
             * @description Уровень спокойствия: 0 — крайне тревожно, 100 — полное спокойствие
             */
            calmness: number;
            /**
             * Format: int32
             * @description Энергия существа: 0 (истощён) — 100 (полон сил)
             */
            energy: number;
            /**
             * Format: int32
             * @description Уровень существа
             */
            level: number;
            /**
             * Format: int32
             * @description Опыт на текущем уровне
             */
            experience: number;
            /**
             * Format: int32
             * @description Текущая серия ежедневных отметок
             */
            streak: number;
            /**
             * Format: date-time
             * @description Дата последнего ежедневного чекина
             */
            lastCheckInAt?: string;
            /**
             * Format: date-time
             * @description Дата последнего дыхательного упражнения
             */
            lastExerciseAt?: string;
            /** @description Текущий выбранный тип питомца */
            petType?: string;
            /** @description Открытые типы питомцев */
            unlockedPetTypes?: string[];
            /** @description Имя питомца, заданное пользователем */
            petName?: string;
            /** @description Активный титул */
            activeTitle?: string;
            /** @description Открытые титулы */
            unlockedTitles?: string[];
            /** @description Активный скин */
            activeSkin?: string;
            /** @description Открытые скины */
            unlockedSkins?: string[];
            /** @description Текущее настроение питомца (happy / calm / support) */
            petMood?: string;
            /** @description Стадия эволюции питомца (baby / kid / adult / max) */
            stage?: string;
            /**
             * Format: int32
             * @description Всего скормленных единиц еды
             */
            feedCount: number;
            /** @description Скормленные единицы по каждому питомцу (map тип → количество) */
            feedCounts: unknown;
            /**
             * Format: int32
             * @description Поглаживаний за текущий день (сбрасывается в полночь по серверному времени)
             */
            petCount: number;
            /**
             * Format: int32
             * @description Сколько поглаживаний осталось сегодня (0 — лимит исчерпан)
             */
            petCountRemaining: number;
            /**
             * Format: int32
             * @description «Утешение» — скрытый параметр, растёт от бонуса «Эмпатия» (грустное настроение)
             */
            comfort: number;
            /**
             * Format: int32
             * @description Токены заморозки стрика: пропуск одного дня при count > 0 не сбрасывает серию
             */
            streakFreezeCount: number;
            /**
             * Format: date-time
             * @description Момент, когда компаньон вернётся с «прогулки» (null — прогулки нет)
             */
            adventureReturnAt?: string;
        };
        /** @description Запись пользователя в технике «Декатастрофизация»: три ответа по шагам декатастрофизации мысли */
        DecatastrophizingEntry: {
            id: string;
            userId: string;
            worstCaseText: string;
            copingPlanText: string;
            mostLikelyText: string;
            /** Format: date-time */
            createdAt: string;
        };
        DecatastrophizingEntryCreate: {
            worstCaseText: string;
            copingPlanText: string;
            mostLikelyText: string;
        };
        /** @description Диада — результат смешивания двух эмоций (алхимия Плутчика) */
        DyadInfo: {
            key: string;
            name: string;
            /**
             * Format: int32
             * @description Уровень диады: 1 первичная, 2 вторичная, 3 третичная, 4 противоположность
             */
            level: number;
            emotions: string[];
        };
        /** @description Эмоция из колеса Плутчика для «Лаборатории эмоций» */
        EmotionInfo: {
            key: string;
            name: string;
        };
        /** @description Тело попытки смешивания двух эмоций */
        EmotionLabAttemptRequest: {
            emotionA: string;
            emotionB: string;
        };
        /** @description Результат попытки смешивания эмоций */
        EmotionLabAttemptResponse: {
            dyad: components["schemas"]["DyadInfo"];
            /** @description Открыта ли диада впервые */
            isNewDiscovery: boolean;
            discoveredDyads: string[];
            /** Format: int32 */
            discoveredCount: number;
            /** Format: int32 */
            totalDyads: number;
            /**
             * Format: int32
             * @description Текущий доступный уровень (1-4) по открытым диадам
             */
            availableLevel: number;
            /** Format: int32 */
            dailyLimit: number;
            /** Format: int32 */
            attemptsUsed: number;
            /** Format: int32 */
            attemptsRemaining: number;
            /**
             * Format: date-time
             * @description Момент сброса дневного лимита (начало следующего дня)
             */
            resetsAt: string;
            tier: string;
            limitReached: boolean;
        };
        /** @description Состояние «Лаборатории эмоций» пользователя */
        EmotionLabState: {
            /** @description Тариф пользователя: free | premium */
            tier: string;
            discoveredDyads: string[];
            /** Format: int32 */
            discoveredCount: number;
            /** Format: int32 */
            totalDyads: number;
            /**
             * Format: int32
             * @description Текущий доступный уровень (1-4) по открытым диадам
             */
            availableLevel: number;
            /** Format: int32 */
            dailyLimit: number;
            /** Format: int32 */
            attemptsUsed: number;
            /** Format: int32 */
            attemptsRemaining: number;
            /**
             * Format: date-time
             * @description Момент сброса дневного лимита (начало следующего дня)
             */
            resetsAt: string;
            limitReached: boolean;
        };
        /** @description Запись значения параметра в конкретный момент времени */
        Entry: {
            id: string;
            userId: string;
            parameterId: string;
            /**
             * Format: double
             * @description Открытое значение — всегда null при E2E-шифровании (данные лежат в encryptedData)
             */
            value: number | null;
            /** @description Открытая заметка — всегда null при E2E-шифровании */
            note?: string | null;
            /** @description Шифротекст {value, note}: base64(version | iv | ciphertext+tag) */
            encryptedData?: string;
            /** Format: date-time */
            createdAt: string;
        };
        EntryCreate: {
            /** @description id генерирует клиент (uuidv7) — используется как entityId в AAD шифрования */
            id: string;
            parameterId: string;
            encryptedData: string;
        };
        EntryUpdate: {
            encryptedData?: string;
        };
        Error: {
            code: string;
            message: string;
        };
        /** @description Результат кормления питомца */
        FeedResponse: {
            state: components["schemas"]["CreatureState"];
            /** @description Был ли достигнут новый уровень */
            leveledUp: boolean;
            /**
             * Format: int32
             * @description Сколько XP начислено за это кормление (0 после дневного лимита)
             */
            xpAwarded: number;
            /**
             * Format: int32
             * @description Всего скормленных единиц еды
             */
            feedCount: number;
            /** @description Скормленные единицы по каждому питомцу (map тип → количество) */
            feedCounts: unknown;
        };
        /** @description Обратная связь от пользователя (сбор ОС) */
        Feedback: {
            id: string;
            userId: string;
            /**
             * Format: int32
             * @description Оценка приложения от 1 до 5
             */
            rating: number;
            message: string;
            /** Format: date-time */
            createdAt: string;
        };
        FeedbackCreate: {
            /**
             * Format: int32
             * @description Оценка приложения от 1 до 5
             */
            rating: number;
            message: string;
        };
        ForgotPasswordRequest: {
            email: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        /** @description Пожелание дня для конкретного пользователя (детерминированная ротация) */
        MessageOfDay: {
            id: string;
            type: string;
            locale: string;
            text: string;
            question?: string | null;
        };
        /** @description Мотивационное пожелание/вопрос для «Моего дня» (утро/вечер), по языкам */
        MotivationMessage: {
            id: string;
            /** @description Тип пожелания: morning | day | evening */
            type: string;
            /** @description Локаль: ru | en */
            locale: string;
            /** @description Мотивационная фраза/пожелание */
            text: string;
            /** @description Опциональный ротируемый вопрос (например, «Как спали?») */
            question?: string | null;
            isActive: boolean;
            /** Format: int32 */
            order: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MotivationMessageCreate: {
            /** @description Тип пожелания: morning | day | evening */
            type: string;
            /** @description Локаль: ru | en */
            locale: string;
            text: string;
            question?: string | null;
            isActive?: boolean;
            /** Format: int32 */
            order?: number;
        };
        MotivationMessageUpdate: {
            type?: string;
            locale?: string;
            text?: string;
            question?: string | null;
            isActive?: boolean;
            /** Format: int32 */
            order?: number;
        };
        /** @description Обучающая история для онбординга новых пользователей после регистрации */
        OnboardingStory: {
            id: string;
            title: string;
            content: string;
            /** Format: int32 */
            order: number;
        };
        /** @description Отслеживаемый параметр ментального здоровья (тревожность, сон, настроение и т.д.). Справочник, задаётся разработчиком/экспертом, не пользователем. */
        Parameter: {
            id: string;
            name: string;
            description?: string;
            unit?: string;
        };
        /** @description Информация о скрытых бонусах за клик по компаньону */
        PetBonus: {
            /** @description Бонус «Бодрое утро» (6:00–12:00 по серверу): 3-й клик дал +2 XP */
            morning: boolean;
            /** @description Бонус «Спокойный вечер» (20:00–23:00): 3-й клик дал +1 XP и +1 calmness */
            evening: boolean;
            /** @description Бонус «Возвращение» (пауза > 4 ч): клик дал +2 XP */
            welcome: boolean;
            /** @description Бонус «Эмпатия» (грустное настроение): 3-й клик дал +1 XP и +2 comfort */
            empathy: boolean;
            /**
             * Format: int32
             * @description Текущая длина серии быстрых кликов (< 0.5 c)
             */
            comboCount: number;
            /** @description На этом клике сработал бонус «Комбо» (+3 XP) */
            comboBonusAwarded: boolean;
            /**
             * Format: int32
             * @description На сколько вырос calmness этим кликом
             */
            calmnessGain: number;
            /**
             * Format: int32
             * @description На сколько вырос comfort этим кликом
             */
            comfortGain: number;
        };
        /** @description Коллекция питомцев пользователя */
        PetCollection: {
            unlockedPetTypes: string[];
            activePetType: string;
            petName: string;
            /** @description Скормленные единицы по каждому питомцу (map тип → количество) */
            feedCounts: unknown;
        };
        /** @description Тело запроса на поглаживание компаньона */
        PetRequest: {
            /** @description Пользователь записал грустное настроение/тревогу — активировать бонус «Эмпатия» */
            empathy?: boolean;
        };
        /** @description Результат поглаживания компаньона */
        PetResponse: {
            state: components["schemas"]["CreatureState"];
            /** @description Был ли достигнут новый уровень */
            leveledUp: boolean;
            /**
             * Format: int32
             * @description Сколько XP начислено за это поглаживание (0 после дневного лимита)
             */
            xpAwarded: number;
            /**
             * Format: int32
             * @description Поглаживаний за текущий день
             */
            petCount: number;
            /**
             * Format: int32
             * @description Сколько поглаживаний осталось сегодня
             */
            petCountRemaining: number;
            /** @description Исчерпан ли дневной лимит поглаживаний */
            limitReached: boolean;
            /**
             * Format: int32
             * @description Позиция в цикле поглаживаний 1-2-3: на 3-й позиции начисляется XP
             */
            cyclePosition: number;
            /**
             * Format: int32
             * @description На сколько вырос calmness этим кликом
             */
            calmnessGain: number;
            /**
             * Format: int32
             * @description На сколько вырос comfort этим кликом
             */
            comfortGain: number;
            /**
             * Format: int32
             * @description Текущая длина серии быстрых кликов (< 0.5 c)
             */
            comboCount: number;
            /** @description На этом клике сработал бонус «Комбо» (+3 XP) */
            comboBonusAwarded: boolean;
            /** @description Скрытые бонусы, сработавшие на этом клике */
            bonus: components["schemas"]["PetBonus"];
        };
        /** @description Тело обновления питомца */
        PetUpdateRequest: {
            /** @description Тип питомца для активации */
            petType?: string;
            /** @description Новое имя питомца (пустая строка очищает) */
            petName?: string;
        };
        /** @description Запись о выполненной практике и полученном опыте */
        PracticeCompletion: {
            source: string;
            /** Format: int32 */
            xpAwarded: number;
            /** Format: date-time */
            createdAt: string;
        };
        RefreshResponse: {
            accessToken: string;
        };
        /** @description Отчёт для выгрузки статистики врачу (PDF/CSV), без участия врача в самом приложении */
        Report: {
            id: string;
            userId: string;
            format: components["schemas"]["ReportFormat"];
            status: components["schemas"]["ReportStatus"];
            /** Format: date-time */
            periodFrom: string;
            /** Format: date-time */
            periodTo: string;
            /** Format: date-time */
            createdAt: string;
            downloadUrl?: string;
        };
        ReportCreate: {
            format: components["schemas"]["ReportFormat"];
            /** Format: date-time */
            periodFrom: string;
            /** Format: date-time */
            periodTo: string;
        };
        /** @enum {string} */
        ReportFormat: "pdf" | "csv";
        /**
         * @description Статус генерации отчёта
         * @enum {string}
         */
        ReportStatus: "pending" | "ready" | "failed";
        /** @description Проверка recovery-материала по токену сброса */
        ResetInfoRequest: {
            token: string;
        };
        /** @description Recovery-ключ (DEK, зашифрованный KEK_recovery) и соль — для восстановления доступа без пароля */
        ResetInfoResponse: {
            recoveryWrappedKey: string | null;
            recoverySalt: string | null;
        };
        ResetPasswordRequest: {
            token: string;
            password: string;
            /** @description DEK, зашифрованный ключом из нового пароля */
            wrappedKey: string;
            /** @description Соль для вывода KEK из нового пароля */
            keySalt: string;
        };
        ResetPasswordResponse: {
            accessToken: string;
            userId: string;
            message: string;
        };
        ResponsibilityFactor: {
            id: string;
            label: string;
            /** Format: int32 */
            percent: number;
        };
        ResponsibilityFactorInput: {
            label: string;
            /** Format: int32 */
            percent: number;
        };
        /** @description Запись пользователя в технике «Пирог ответственности»: ситуация + разбивка ответственности по факторам (в сумме 100) */
        ResponsibilityPieEntry: {
            id: string;
            userId: string;
            situationText: string;
            /** Format: date-time */
            createdAt: string;
            factors: components["schemas"]["ResponsibilityFactor"][];
        };
        ResponsibilityPieEntryCreate: {
            situationText: string;
            factors: components["schemas"]["ResponsibilityFactorInput"][];
        };
        /** @description Запрос на награду за практику */
        RewardRequest: {
            source: string;
        };
        /** @description Результат награды за практику */
        RewardResponse: {
            state: components["schemas"]["CreatureState"];
            /** @description Был ли достигнут новый уровень */
            leveledUp: boolean;
        };
        SetKeysOk: {
            ok: boolean;
        };
        /** @description E2E-ключи для миграции legacy-учётки (созданной до внедрения шифрования) */
        SetKeysRequest: {
            /** @description DEK, зашифрованный ключом из пароля */
            wrappedKey: string;
            /** @description Соль для вывода KEK из пароля */
            keySalt: string;
            /** @description DEK, зашифрованный ключом из recovery-кода */
            recoveryWrappedKey: string;
            /** @description Соль для вывода KEK из recovery-кода */
            recoverySalt: string;
        };
        /** @description Психологический тест, построенный на справочниках/книгах по психологии. Шаблон: вопросы + правила подсчёта баллов. */
        Test: {
            id: string;
            title: string;
            description?: string;
            active: boolean;
            questions: components["schemas"]["TestQuestion"][];
            /** @description Тип подсчёта: standard (баллы) / computed (профиль когнитивных искажений) */
            type: string;
            /** @description Полосы интерпретации для standard-тестов (клиент считает результат локально) */
            scoreBands: components["schemas"]["TestScoreBand"][];
        };
        TestAnswer: {
            questionId: string;
            optionId: string;
        };
        TestDigest: {
            id: string;
            title: string;
            description?: string;
            active: boolean;
        };
        TestQuestion: {
            id: string;
            text: string;
            options: components["schemas"]["TestQuestionOption"][];
        };
        TestQuestionOption: {
            id: string;
            text: string;
            /** Format: int32 */
            score: number;
        };
        /** @description Конкретная попытка прохождения теста пользователем: результат в E2E-шифротексте */
        TestResult: {
            id: string;
            testId: string;
            userId: string;
            /**
             * Format: int32
             * @description Открытый балл — всегда null при E2E-шифровании (данные лежат в encryptedData)
             */
            score: number | null;
            /** @description Открытая интерпретация — всегда null при E2E-шифровании */
            interpretation: string | null;
            /** @description Открытая рекомендация — всегда null при E2E-шифровании */
            recommendation: string | null;
            /** @description Открытые флаги/профили — всегда null при E2E-шифровании */
            flags?: unknown;
            /** @description Шифротекст {score, interpretation, recommendation, flags} */
            encryptedData?: string;
            /** Format: date-time */
            completedAt: string;
        };
        /** @description Полоса баллов с интерпретацией для теста */
        TestScoreBand: {
            /** Format: int32 */
            maxScore: number;
            key: string;
            interpretation: string;
            recommendation: string;
        };
        /** @description Пользователь приложения */
        User: {
            id: string;
            email: string;
            name?: string;
            role: string;
            /** Format: date-time */
            createdAt: string;
        };
        UserCreate: {
            email: string;
            password: string;
            name?: string;
            ageConfirmed: boolean;
            pdpConsent: boolean;
            /** Format: int32 */
            birthYear?: number;
            /** @description DEK, зашифрованный ключом, выведенным из пароля (AES-GCM) */
            wrappedKey: string;
            /** @description Соль для вывода KEK из пароля */
            keySalt: string;
            /** @description DEK, зашифрованный ключом, выведенным из recovery-кода */
            recoveryWrappedKey: string;
            /** @description Соль для вывода KEK_recovery из recovery-кода */
            recoverySalt: string;
        };
        /** @description Настройки и предпочтения пользователя */
        UserPreference: {
            goals: string[];
            experienceLevel: string;
            dailyReminder: boolean;
            reminderTime?: string;
            afternoonReminder: boolean;
            afternoonTime?: string;
            eveningReminder: boolean;
            eveningTime?: string;
            onboardingDone: boolean;
        };
        UserPreferenceUpdate: {
            goals?: string[];
            experienceLevel?: string;
            dailyReminder?: boolean;
            reminderTime?: string;
            afternoonReminder?: boolean;
            afternoonTime?: string;
            eveningReminder?: boolean;
            eveningTime?: string;
            onboardingDone?: boolean;
        };
        UserUpdate: {
            name?: string;
        };
        /** @description Один день недельного календаря практик (Пн–Вс) */
        WeeklyDay: {
            /** @description Дата дня (YYYY-MM-DD) */
            date: string;
            /**
             * Format: int32
             * @description Индекс дня недели: 0=Пн … 6=Вс
             */
            dayOfWeek: number;
            /** @description Была ли в этот день засчитана практика/чек-ин */
            completed: boolean;
            isToday: boolean;
            isFuture: boolean;
        };
        /** @description Недельный календарь практик: неделя Пн–Вс, цель — N дней, подарок +XP */
        WeeklyState: {
            /** @description Дата понедельника текущей недели (YYYY-MM-DD) */
            weekStart: string;
            days: components["schemas"]["WeeklyDay"][];
            /**
             * Format: int32
             * @description Сколько уникальных дней недели засчитано
             */
            completedCount: number;
            /**
             * Format: int32
             * @description Цель в днях для получения подарка
             */
            goal: number;
            /** @description Цель уже достигнута в этой неделе */
            goalReached: boolean;
            /** @description Подарок за эту неделю уже забран */
            claimed: boolean;
            /**
             * Format: int32
             * @description Сколько XP даёт подарок
             */
            xpReward: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdminUsers_listFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminFeedback"][];
                };
            };
        };
    };
    AdminUsers_listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"][];
                };
            };
        };
    };
    AdminUsers_deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminUsers_updateUserTier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserTierUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserTierResult"];
                };
            };
        };
    };
    Auth_forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    Auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Auth_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
        };
    };
    Auth_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    Auth_resetInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetInfoRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetInfoResponse"];
                };
            };
        };
    };
    Auth_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetPasswordResponse"];
                };
            };
        };
    };
    Auth_setKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetKeysRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetKeysOk"];
                };
            };
        };
    };
    Cba_listCommonItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CbaCommonItem"][];
                };
            };
        };
    };
    Cba_listEntries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CbaEntry"][];
                };
            };
        };
    };
    Cba_createEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CbaEntryCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CbaEntry"];
                };
            };
        };
    };
    Cba_deleteEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Cba_listExamples: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CbaExample"][];
                };
            };
        };
    };
    Content_messageOfDay: {
        parameters: {
            query: {
                type: string;
                locale: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOfDay"];
                };
            };
        };
    };
    Content_listMessages: {
        parameters: {
            query?: {
                type?: string;
                locale?: string;
                active?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MotivationMessage"][];
                };
            };
        };
    };
    Content_createMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MotivationMessageCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MotivationMessage"];
                };
            };
        };
    };
    Content_deleteMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Content_updateMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MotivationMessageUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MotivationMessage"];
                };
            };
        };
    };
    Creature_getState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatureState"];
                };
            };
        };
    };
    Creature_claimAdventure: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimAdventureResponse"];
                };
            };
        };
    };
    Creature_checkIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInResponse"];
                };
            };
        };
    };
    Creature_getCompletions: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeCompletion"][];
                };
            };
        };
    };
    Creature_completeExercise: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BreathingCompleteRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInResponse"];
                };
            };
        };
    };
    Creature_pet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PetRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PetResponse"];
                };
            };
        };
    };
    Creature_setPet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PetUpdateRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PetCollection"];
                };
            };
        };
    };
    Creature_getPets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PetCollection"];
                };
            };
        };
    };
    Creature_reward: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RewardRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RewardResponse"];
                };
            };
        };
    };
    Creature_getWeekly: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyState"];
                };
            };
        };
    };
    Creature_claimWeekly: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimWeeklyResponse"];
                };
            };
        };
    };
    Decatastrophizing_listEntries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecatastrophizingEntry"][];
                };
            };
        };
    };
    Decatastrophizing_createEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecatastrophizingEntryCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecatastrophizingEntry"];
                };
            };
        };
    };
    Decatastrophizing_deleteEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmotionLab_attempt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmotionLabAttemptRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmotionLabAttemptResponse"];
                };
            };
        };
    };
    EmotionLab_getState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmotionLabState"];
                };
            };
        };
    };
    Entries_list: {
        parameters: {
            query?: {
                parameterId?: string;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"][];
                };
            };
        };
    };
    Entries_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
        };
    };
    Entries_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
        };
    };
    Entries_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Entries_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
        };
    };
    FeedbackApi_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"];
                };
            };
        };
    };
    FeedbackApi_listMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"][];
                };
            };
        };
    };
    OnboardingStories_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingStory"][];
                };
            };
        };
    };
    Parameters_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Parameter"][];
                };
            };
        };
    };
    Reports_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"][];
                };
            };
        };
    };
    Reports_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
        };
    };
    Reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
        };
    };
    Reports_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Reports_download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    ResponsibilityPie_listEntries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponsibilityPieEntry"][];
                };
            };
        };
    };
    ResponsibilityPie_createEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResponsibilityPieEntryCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponsibilityPieEntry"];
                };
            };
        };
    };
    ResponsibilityPie_deleteEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TestResults_list: {
        parameters: {
            query?: {
                testId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestResult"][];
                };
            };
        };
    };
    TestResults_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestResult"];
                };
            };
        };
    };
    Tests_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestDigest"][];
                };
            };
        };
    };
    Tests_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Test"];
                };
            };
        };
    };
    Users_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    Users_deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Users_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    Users_getPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreference"];
                };
            };
        };
    };
    Users_savePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPreferenceUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreference"];
                };
            };
        };
    };
}
