import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  Angry,
  Apple,
  Archive,
  ArrowLeftRight,
  Baby,
  Banknote,
  Bath,
  BatteryLow,
  BedDouble,
  Bike,
  Bird,
  BookCheck,
  BookOpen,
  Briefcase,
  Brush,
  Cake,
  CalendarOff,
  Camera,
  Car,
  CheckCircle,
  ChefHat,
  Church,
  Clapperboard,
  ClipboardList,
  Clock,
  CloudDrizzle,
  CloudLightning,
  CloudRainWind,
  Coffee,
  Crosshair,
  Croissant,
  Dumbbell,
  Eye,
  Flower2,
  Frown,
  Footprints,
  Gamepad2,
  Gift,
  GlassWater,
  GraduationCap,
  Hammer,
  HandHeart,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  Home,
  Laptop,
  Landmark,
  Leaf,
  Lightbulb,
  LogOut,
  MapPin,
  MessageCircle,
  MessageSquareHeart,
  Mic,
  Moon,
  MoonStar,
  Mountain,
  Music,
  PartyPopper,
  Pen,
  PenLine,
  PersonStanding,
  Phone,
  Pill,
  Plane,
  Presentation,
  Puzzle,
  Rocket,
  RotateCcw,
  Scissors,
  Share2,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Smile,
  Snowflake,
  Sparkles,
  Sprout,
  Stethoscope,
  Store,
  Sun,
  Sunrise,
  Target,
  Tent,
  Thermometer,
  Ticket,
  Timer,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  UserCheck,
  UserPlus,
  Users,
  UserX,
  UsersRound,
  Utensils,
  Waves,
  Wind,
  Wine,
  Zap,
  Boxes,
  CalendarCheck,
  Castle,
  Clock3,
  CloudRain,
  Cog,
  Cookie,
  Droplet,
  Flag,
  Flame,
  FoldHorizontal,
  Layers,
  Monitor,
  Palette,
  PawPrint,
  PenTool,
  Salad,
  Syringe,
  TestTube,
  ThumbsUp,
  Trees,
  Video,
  Wrench,
} from 'lucide-react';

export enum ActivityCategory {
  Work = 'work',
  Study = 'study',
  Health = 'health',
  Movement = 'movement',
  Rest = 'rest',
  Social = 'social',
  Hobby = 'hobby',
  Events = 'events',
  Wellbeing = 'wellbeing',
}

export const CATEGORY_ICONS: Record<ActivityCategory, LucideIcon> = {
  [ActivityCategory.Work]: Briefcase,
  [ActivityCategory.Study]: GraduationCap,
  [ActivityCategory.Health]: HeartPulse,
  [ActivityCategory.Movement]: Dumbbell,
  [ActivityCategory.Rest]: Moon,
  [ActivityCategory.Social]: Users,
  [ActivityCategory.Hobby]: Music,
  [ActivityCategory.Events]: PartyPopper,
  [ActivityCategory.Wellbeing]: Sparkles,
};

export interface DayActivityDefinition {
  key: string;
  category: ActivityCategory;
  labelKey: string;
}

// Wellbeing («как ты себя чувствуешь») больше не предлагается при выборе —
// это дублировало числовую шкалу Mood и теперь закрывается тегами эмоций
// из Лаборатории эмоций (см. EmotionTagPicker). Сама категория и её записи
// ниже НЕ удалены — так уже сохранённые исторические ActivitySelection с
// ключами wellbeing.* продолжают корректно отображаться (иконка + перевод)
// везде, где есть история активностей (ActivityCorrelationCard и т.п.).
export const ACTIVITY_CATEGORY_ORDER: ActivityCategory[] = [
  ActivityCategory.Work,
  ActivityCategory.Study,
  ActivityCategory.Health,
  ActivityCategory.Movement,
  ActivityCategory.Rest,
  ActivityCategory.Social,
  ActivityCategory.Hobby,
  ActivityCategory.Events,
];

const CAT: Record<ActivityCategory, ActivityCategory> = {
  work: ActivityCategory.Work,
  study: ActivityCategory.Study,
  health: ActivityCategory.Health,
  movement: ActivityCategory.Movement,
  rest: ActivityCategory.Rest,
  social: ActivityCategory.Social,
  hobby: ActivityCategory.Hobby,
  events: ActivityCategory.Events,
  wellbeing: ActivityCategory.Wellbeing,
};

function def(categoryKey: ActivityCategory, key: string): DayActivityDefinition {
  return {
    key: `${categoryKey}.${key}`,
    category: CAT[categoryKey],
    labelKey: `dayActivities.activities.${categoryKey}_${key}`,
  };
}

export const ACTIVITY_CATALOG: DayActivityDefinition[] = [
  def(ActivityCategory.Work, 'worked'),
  def(ActivityCategory.Work, 'meeting'),
  def(ActivityCategory.Work, 'deadline'),
  def(ActivityCategory.Work, 'presentation'),
  def(ActivityCategory.Work, 'overtime'),
  def(ActivityCategory.Work, 'day_off'),
  def(ActivityCategory.Work, 'remote'),
  def(ActivityCategory.Work, 'stressful_day'),
  def(ActivityCategory.Work, 'success'),
  def(ActivityCategory.Work, 'new_project'),
  def(ActivityCategory.Work, 'salary'),
  def(ActivityCategory.Work, 'business_trip'),
  def(ActivityCategory.Work, 'employee_review'),
  def(ActivityCategory.Work, 'hired'),
  def(ActivityCategory.Work, 'quitting'),
  def(ActivityCategory.Work, 'promotion'),
  def(ActivityCategory.Work, 'bad_boss'),
  def(ActivityCategory.Work, 'fired'),
  def(ActivityCategory.Work, 'lunch_with_colleagues'),
  def(ActivityCategory.Work, 'focus_day'),
  def(ActivityCategory.Work, 'remote_stress'),
  def(ActivityCategory.Work, 'team_success'),
  def(ActivityCategory.Study, 'studied'),
  def(ActivityCategory.Study, 'exam'),
  def(ActivityCategory.Study, 'homework'),
  def(ActivityCategory.Study, 'course'),
  def(ActivityCategory.Study, 'listened_lecture'),
  def(ActivityCategory.Study, 'failed_exam'),
  def(ActivityCategory.Study, 'passed_exam'),
  def(ActivityCategory.Study, 'learned_skill'),
  def(ActivityCategory.Study, 'read_textbook'),
  def(ActivityCategory.Study, 'conference'),
  def(ActivityCategory.Study, 'workshop'),
  def(ActivityCategory.Study, 'language_lesson'),
  def(ActivityCategory.Study, 'research'),
  def(ActivityCategory.Health, 'doctor_visit'),
  def(ActivityCategory.Health, 'therapy_session'),
  def(ActivityCategory.Health, 'medication'),
  def(ActivityCategory.Health, 'sick'),
  def(ActivityCategory.Health, 'headache'),
  def(ActivityCategory.Health, 'good_health'),
  def(ActivityCategory.Health, 'bad_sleep'),
  def(ActivityCategory.Health, 'good_sleep'),
  def(ActivityCategory.Health, 'toothache'),
  def(ActivityCategory.Health, 'flu'),
  def(ActivityCategory.Health, 'dental_visit'),
  def(ActivityCategory.Health, 'eye_strain'),
  def(ActivityCategory.Health, 'digestion'),
  def(ActivityCategory.Health, 'allergy'),
  def(ActivityCategory.Health, 'massage'),
  def(ActivityCategory.Health, 'gratitude_health'),
  def(ActivityCategory.Health, 'energy_drop'),
  def(ActivityCategory.Health, 'caffeine'),
  def(ActivityCategory.Health, 'alcohol'),
  def(ActivityCategory.Movement, 'walk'),
  def(ActivityCategory.Movement, 'gym'),
  def(ActivityCategory.Movement, 'run'),
  def(ActivityCategory.Movement, 'yoga'),
  def(ActivityCategory.Movement, 'cycling'),
  def(ActivityCategory.Movement, 'sport_game'),
  def(ActivityCategory.Movement, 'home_workout'),
  def(ActivityCategory.Movement, 'stretching'),
  def(ActivityCategory.Movement, 'dance'),
  def(ActivityCategory.Movement, 'swimming'),
  def(ActivityCategory.Movement, 'hiking'),
  def(ActivityCategory.Movement, 'pilates'),
  def(ActivityCategory.Movement, 'boxing'),
  def(ActivityCategory.Movement, 'tennis'),
  def(ActivityCategory.Movement, 'basketball'),
  def(ActivityCategory.Movement, 'football'),
  def(ActivityCategory.Movement, 'skateboard'),
  def(ActivityCategory.Movement, 'ski'),
  def(ActivityCategory.Movement, 'climbing'),
  def(ActivityCategory.Movement, 'sports_outdoor'),
  def(ActivityCategory.Rest, 'read'),
  def(ActivityCategory.Rest, 'watched_movie'),
  def(ActivityCategory.Rest, 'watched_tv'),
  def(ActivityCategory.Rest, 'played_games'),
  def(ActivityCategory.Rest, 'listened_music'),
  def(ActivityCategory.Rest, 'nap'),
  def(ActivityCategory.Rest, 'relaxed'),
  def(ActivityCategory.Rest, 'mobile_scroll'),
  def(ActivityCategory.Rest, 'walked_leisure'),
  def(ActivityCategory.Rest, 'stay_in'),
  def(ActivityCategory.Rest, 'hot_bath'),
  def(ActivityCategory.Rest, 'meditation'),
  def(ActivityCategory.Rest, 'quiet_morning'),
  def(ActivityCategory.Rest, 'social_media'),
  def(ActivityCategory.Social, 'friends'),
  def(ActivityCategory.Social, 'family'),
  def(ActivityCategory.Social, 'partner'),
  def(ActivityCategory.Social, 'helped_others'),
  def(ActivityCategory.Social, 'phone_call'),
  def(ActivityCategory.Social, 'conflict'),
  def(ActivityCategory.Social, 'date'),
  def(ActivityCategory.Social, 'kids'),
  def(ActivityCategory.Social, 'parents'),
  def(ActivityCategory.Social, 'colleagues'),
  def(ActivityCategory.Social, 'new_acquaintance'),
  def(ActivityCategory.Social, 'reunion'),
  def(ActivityCategory.Social, 'neighbors'),
  def(ActivityCategory.Social, 'party'),
  def(ActivityCategory.Social, 'networking'),
  def(ActivityCategory.Social, 'support_group'),
  def(ActivityCategory.Social, 'lonely'),
  def(ActivityCategory.Social, 'good_communication'),
  def(ActivityCategory.Hobby, 'drawing'),
  def(ActivityCategory.Hobby, 'music_playing'),
  def(ActivityCategory.Hobby, 'cooking'),
  def(ActivityCategory.Hobby, 'gaming'),
  def(ActivityCategory.Hobby, 'photography'),
  def(ActivityCategory.Hobby, 'writing'),
  def(ActivityCategory.Hobby, 'diy'),
  def(ActivityCategory.Hobby, 'knitting'),
  def(ActivityCategory.Hobby, 'gardening'),
  def(ActivityCategory.Hobby, 'puzzle'),
  def(ActivityCategory.Hobby, 'board_games'),
  def(ActivityCategory.Hobby, 'collecting'),
  def(ActivityCategory.Hobby, 'pottery'),
  def(ActivityCategory.Hobby, 'painting'),
  def(ActivityCategory.Hobby, 'singing'),
  def(ActivityCategory.Hobby, 'rebuild_car'),
  def(ActivityCategory.Hobby, 'build_model'),
  def(ActivityCategory.Hobby, 'crafts'),
  def(ActivityCategory.Events, 'celebration'),
  def(ActivityCategory.Events, 'holiday'),
  def(ActivityCategory.Events, 'travel'),
  def(ActivityCategory.Events, 'concert'),
  def(ActivityCategory.Events, 'wedding'),
  def(ActivityCategory.Events, 'shopping'),
  def(ActivityCategory.Events, 'birthday'),
  def(ActivityCategory.Events, 'anniversary'),
  def(ActivityCategory.Events, 'graduation'),
  def(ActivityCategory.Events, 'sport_event'),
  def(ActivityCategory.Events, 'theater'),
  def(ActivityCategory.Events, 'museum'),
  def(ActivityCategory.Events, 'city_trip'),
  def(ActivityCategory.Events, 'market'),
  def(ActivityCategory.Events, 'religious_day'),
  def(ActivityCategory.Events, 'special_meal'),
  def(ActivityCategory.Wellbeing, 'stress'),
  def(ActivityCategory.Wellbeing, 'anxiety'),
  def(ActivityCategory.Wellbeing, 'good_mood'),
  def(ActivityCategory.Wellbeing, 'low_mood'),
  def(ActivityCategory.Wellbeing, 'grateful'),
  def(ActivityCategory.Wellbeing, 'peaceful'),
  def(ActivityCategory.Wellbeing, 'overwhelmed'),
  def(ActivityCategory.Wellbeing, 'energetic'),
  def(ActivityCategory.Wellbeing, 'tired'),
  def(ActivityCategory.Wellbeing, 'rainy_day'),
  def(ActivityCategory.Wellbeing, 'sunny_day'),
  def(ActivityCategory.Wellbeing, 'motivated'),
  def(ActivityCategory.Wellbeing, 'hopeful'),
  def(ActivityCategory.Wellbeing, 'sad'),
  def(ActivityCategory.Wellbeing, 'angry'),
  def(ActivityCategory.Wellbeing, 'irritated'),
  def(ActivityCategory.Wellbeing, 'calm'),
  def(ActivityCategory.Wellbeing, 'stress_relief'),
  def(ActivityCategory.Wellbeing, 'breakthrough'),
  def(ActivityCategory.Wellbeing, 'self_care'),
  def(ActivityCategory.Wellbeing, 'rush'),
  def(ActivityCategory.Wellbeing, 'satisfied'),
  def(ActivityCategory.Wellbeing, 'lonely_day'),
  def(ActivityCategory.Wellbeing, 'wild_day'),
  def(ActivityCategory.Wellbeing, 'routine_day'),
  def(ActivityCategory.Work, 'telework_balance'),
  def(ActivityCategory.Work, 'boring_day'),
  def(ActivityCategory.Work, 'insight_work'),
  def(ActivityCategory.Study, 'online_lesson'),
  def(ActivityCategory.Study, 'self_education'),
  def(ActivityCategory.Study, 'group_project'),
  def(ActivityCategory.Health, 'vitamins'),
  def(ActivityCategory.Health, 'sleep_eight'),
  def(ActivityCategory.Health, 'hydration'),
  def(ActivityCategory.Health, 'fresh_air'),
  def(ActivityCategory.Movement, 'morning_run'),
  def(ActivityCategory.Movement, 'stairs'),
  def(ActivityCategory.Movement, 'team_sport'),
  def(ActivityCategory.Rest, 'sat_outdoors'),
  def(ActivityCategory.Rest, 'tea_ceremony'),
  def(ActivityCategory.Rest, 'silence'),
  def(ActivityCategory.Social, 'cooked_for_others'),
  def(ActivityCategory.Social, 'thanks_text'),
  def(ActivityCategory.Social, 'visit'),
  def(ActivityCategory.Hobby, 'baking'),
  def(ActivityCategory.Hobby, 'fishing'),
  def(ActivityCategory.Hobby, 'birdwatching'),
  def(ActivityCategory.Events, 'city_festival'),
  def(ActivityCategory.Events, 'first_snow'),
  def(ActivityCategory.Events, 'moved'),
  def(ActivityCategory.Wellbeing, 'fresh_start'),
  def(ActivityCategory.Wellbeing, 'slept_early'),
  def(ActivityCategory.Wellbeing, 'mood_swing'),
  def(ActivityCategory.Wellbeing, 'confidence'),
  def(ActivityCategory.Work, 'sprint'),
  def(ActivityCategory.Work, 'standup'),
  def(ActivityCategory.Work, 'retro'),
  def(ActivityCategory.Work, 'mentoring'),
  def(ActivityCategory.Work, 'code_review'),
  def(ActivityCategory.Work, 'new_tool'),
  def(ActivityCategory.Work, 'planning'),
  def(ActivityCategory.Work, 'deadline_met'),
  def(ActivityCategory.Work, 'missed_deadline'),
  def(ActivityCategory.Work, 'conflict'),
  def(ActivityCategory.Work, 'praise'),
  def(ActivityCategory.Work, 'crunch'),
  def(ActivityCategory.Work, 'slow_day'),
  def(ActivityCategory.Work, 'home_office'),
  def(ActivityCategory.Work, 'remote_call'),
  def(ActivityCategory.Work, 'internship'),
  def(ActivityCategory.Work, 'freelance'),
  def(ActivityCategory.Work, 'side_project'),
  def(ActivityCategory.Work, 'team_building'),
  def(ActivityCategory.Work, 'boring_task'),
  def(ActivityCategory.Study, 'flashcards'),
  def(ActivityCategory.Study, 'notes'),
  def(ActivityCategory.Study, 'webinar'),
  def(ActivityCategory.Study, 'online_course'),
  def(ActivityCategory.Study, 'mentor'),
  def(ActivityCategory.Study, 'practice'),
  def(ActivityCategory.Study, 'project'),
  def(ActivityCategory.Study, 'group_work'),
  def(ActivityCategory.Study, 'revision'),
  def(ActivityCategory.Study, 'mistake'),
  def(ActivityCategory.Study, 'success_study'),
  def(ActivityCategory.Study, 'motivation'),
  def(ActivityCategory.Study, 'burnout'),
  def(ActivityCategory.Study, 'schedule'),
  def(ActivityCategory.Study, 'exam_prep'),
  def(ActivityCategory.Study, 'deadline_study'),
  def(ActivityCategory.Study, 'discussion'),
  def(ActivityCategory.Study, 'focus_study'),
  def(ActivityCategory.Study, 'reading'),
  def(ActivityCategory.Study, 'digital_notes'),
  def(ActivityCategory.Health, 'checkup'),
  def(ActivityCategory.Health, 'blood_test'),
  def(ActivityCategory.Health, 'physio'),
  def(ActivityCategory.Health, 'osteopath'),
  def(ActivityCategory.Health, 'vaccine'),
  def(ActivityCategory.Health, 'acupuncture'),
  def(ActivityCategory.Health, 'eye_test'),
  def(ActivityCategory.Health, 'healthy_meal'),
  def(ActivityCategory.Health, 'junk_food'),
  def(ActivityCategory.Health, 'less_sugar'),
  def(ActivityCategory.Health, 'stretching'),
  def(ActivityCategory.Health, 'breathing'),
  def(ActivityCategory.Health, 'cold_shower'),
  def(ActivityCategory.Health, 'sauna'),
  def(ActivityCategory.Health, 'sunlight'),
  def(ActivityCategory.Health, 'meditation'),
  def(ActivityCategory.Health, 'sleep_disrupted'),
  def(ActivityCategory.Health, 'sleep_late'),
  def(ActivityCategory.Health, 'phone_before_sleep'),
  def(ActivityCategory.Health, 'regular_meal'),
  def(ActivityCategory.Movement, 'walk_park'),
  def(ActivityCategory.Movement, 'sprints'),
  def(ActivityCategory.Movement, 'pingpong'),
  def(ActivityCategory.Movement, 'badminton'),
  def(ActivityCategory.Movement, 'volleyball'),
  def(ActivityCategory.Movement, 'hockey'),
  def(ActivityCategory.Movement, 'skating'),
  def(ActivityCategory.Movement, 'rollers'),
  def(ActivityCategory.Movement, 'trampoline'),
  def(ActivityCategory.Movement, 'calisthenics'),
  def(ActivityCategory.Movement, 'hiit'),
  def(ActivityCategory.Movement, 'crossfit'),
  def(ActivityCategory.Movement, 'tai_chi'),
  def(ActivityCategory.Movement, 'horse'),
  def(ActivityCategory.Movement, 'rowing'),
  def(ActivityCategory.Movement, 'rock_climb'),
  def(ActivityCategory.Movement, 'dance_class'),
  def(ActivityCategory.Movement, 'gym_light'),
  def(ActivityCategory.Movement, 'workout_outside'),
  def(ActivityCategory.Movement, 'strength'),
  def(ActivityCategory.Rest, 'audiobook'),
  def(ActivityCategory.Rest, 'podcast'),
  def(ActivityCategory.Rest, 'sleep_long'),
  def(ActivityCategory.Rest, 'cozy'),
  def(ActivityCategory.Rest, 'stargazing'),
  def(ActivityCategory.Rest, 'picnic'),
  def(ActivityCategory.Rest, 'camping'),
  def(ActivityCategory.Rest, 'chess'),
  def(ActivityCategory.Rest, 'cards'),
  def(ActivityCategory.Rest, 'karaoke'),
  def(ActivityCategory.Rest, 'sauna_rest'),
  def(ActivityCategory.Rest, 'lazy_day'),
  def(ActivityCategory.Rest, 'sunbathing'),
  def(ActivityCategory.Rest, 'fishing'),
  def(ActivityCategory.Rest, 'birdwatching'),
  def(ActivityCategory.Rest, 'balcony'),
  def(ActivityCategory.Rest, 'library'),
  def(ActivityCategory.Rest, 'quiet_cafe'),
  def(ActivityCategory.Rest, 'painting_rest'),
  def(ActivityCategory.Rest, 'dance_rest'),
  def(ActivityCategory.Social, 'group_chat'),
  def(ActivityCategory.Social, 'video_call'),
  def(ActivityCategory.Social, 'online_game'),
  def(ActivityCategory.Social, 'sibling'),
  def(ActivityCategory.Social, 'grandparents'),
  def(ActivityCategory.Social, 'pet'),
  def(ActivityCategory.Social, 'volunteer'),
  def(ActivityCategory.Social, 'mentor_social'),
  def(ActivityCategory.Social, 'boundary'),
  def(ActivityCategory.Social, 'apology'),
  def(ActivityCategory.Social, 'gift_social'),
  def(ActivityCategory.Social, 'congratulated'),
  def(ActivityCategory.Social, 'work_event'),
  def(ActivityCategory.Social, 'community'),
  def(ActivityCategory.Social, 'help_stranger'),
  def(ActivityCategory.Social, 'meetup'),
  def(ActivityCategory.Social, 'photo_call'),
  def(ActivityCategory.Social, 'voice'),
  def(ActivityCategory.Social, 'hug'),
  def(ActivityCategory.Social, 'heart_to_heart'),
  def(ActivityCategory.Hobby, 'embroidery'),
  def(ActivityCategory.Hobby, 'beading'),
  def(ActivityCategory.Hobby, 'macrame'),
  def(ActivityCategory.Hobby, 'resin'),
  def(ActivityCategory.Hobby, 'soap'),
  def(ActivityCategory.Hobby, 'candles'),
  def(ActivityCategory.Hobby, 'origami'),
  def(ActivityCategory.Hobby, 'calligraphy'),
  def(ActivityCategory.Hobby, 'woodwork'),
  def(ActivityCategory.Hobby, 'metalwork'),
  def(ActivityCategory.Hobby, 'print3d'),
  def(ActivityCategory.Hobby, 'robotics'),
  def(ActivityCategory.Hobby, 'drone'),
  def(ActivityCategory.Hobby, 'simulators'),
  def(ActivityCategory.Hobby, 'escape_room'),
  def(ActivityCategory.Hobby, 'chess_hobby'),
  def(ActivityCategory.Hobby, 'stamps'),
  def(ActivityCategory.Hobby, 'kayak'),
  def(ActivityCategory.Hobby, 'mushrooms'),
  def(ActivityCategory.Hobby, 'fishing_hobby'),
  def(ActivityCategory.Events, 'exhibition'),
  def(ActivityCategory.Events, 'premiere'),
  def(ActivityCategory.Events, 'opera'),
  def(ActivityCategory.Events, 'ballet'),
  def(ActivityCategory.Events, 'festival'),
  def(ActivityCategory.Events, 'parade'),
  def(ActivityCategory.Events, 'carnival'),
  def(ActivityCategory.Events, 'fireworks'),
  def(ActivityCategory.Events, 'book_fair'),
  def(ActivityCategory.Events, 'food_festival'),
  def(ActivityCategory.Events, 'gala'),
  def(ActivityCategory.Events, 'retreat'),
  def(ActivityCategory.Events, 'family_gathering'),
  def(ActivityCategory.Events, 'visit_relatives'),
  def(ActivityCategory.Events, 'open_air'),
  def(ActivityCategory.Events, 'standup_comedy'),
  def(ActivityCategory.Events, 'kids_party'),
  def(ActivityCategory.Events, 'charity_event'),
  def(ActivityCategory.Events, 'contest'),
  def(ActivityCategory.Events, 'holiday_home'),
  def(ActivityCategory.Wellbeing, 'breathing_well'),
  def(ActivityCategory.Wellbeing, 'journaling'),
  def(ActivityCategory.Wellbeing, 'affirmations'),
  def(ActivityCategory.Wellbeing, 'digital_detox'),
  def(ActivityCategory.Wellbeing, 'nature'),
  def(ActivityCategory.Wellbeing, 'cold_shower_well'),
  def(ActivityCategory.Wellbeing, 'sunlight_well'),
  def(ActivityCategory.Wellbeing, 'gratitude_well'),
  def(ActivityCategory.Wellbeing, 'positive'),
  def(ActivityCategory.Wellbeing, 'boundaries_well'),
  def(ActivityCategory.Wellbeing, 'self_care_extra'),
  def(ActivityCategory.Wellbeing, 'routine'),
  def(ActivityCategory.Wellbeing, 'music_well'),
  def(ActivityCategory.Wellbeing, 'art_therapy'),
  def(ActivityCategory.Wellbeing, 'reading_well'),
  def(ActivityCategory.Wellbeing, 'mindful_walk'),
  def(ActivityCategory.Wellbeing, 'social_joy'),
  def(ActivityCategory.Wellbeing, 'cried'),
  def(ActivityCategory.Wellbeing, 'let_off_steam'),
  def(ActivityCategory.Wellbeing, 'smiled'),
];

// Куратированное подмножество каталога (~18-20 на категорию вместо ~40) —
// показывается при обычном просмотре категории, чтобы не перегружать выбор
// (см. Hick's law / chunking). Полный каталог по-прежнему доступен через
// поиск внутри категории (см. filteredByCategory в DayActivitiesSection) —
// ничего не удалено, просто не всё показывается сразу по умолчанию.
// Также здесь устранены смысловые дубли между категориями (например,
// «Растяжка» была одновременно в Health и Movement) — каждый пункт
// оставлен в одной, наиболее уместной категории.
const CORE_ACTIVITY_KEYS = new Set<string>([
  // Work
  'work.worked',
  'work.meeting',
  'work.deadline',
  'work.presentation',
  'work.overtime',
  'work.day_off',
  'work.remote',
  'work.stressful_day',
  'work.success',
  'work.new_project',
  'work.business_trip',
  'work.promotion',
  'work.bad_boss',
  'work.fired',
  'work.focus_day',
  'work.praise',
  'work.crunch',
  'work.freelance',
  'work.team_building',
  // Study
  'study.studied',
  'study.exam',
  'study.homework',
  'study.course',
  'study.failed_exam',
  'study.passed_exam',
  'study.learned_skill',
  'study.workshop',
  'study.language_lesson',
  'study.online_lesson',
  'study.self_education',
  'study.notes',
  'study.practice',
  'study.revision',
  'study.mistake',
  'study.motivation',
  'study.burnout',
  'study.exam_prep',
  // Health (stretching живёт в Movement, meditation оставлена здесь)
  'health.doctor_visit',
  'health.therapy_session',
  'health.medication',
  'health.sick',
  'health.headache',
  'health.good_health',
  'health.bad_sleep',
  'health.good_sleep',
  'health.dental_visit',
  'health.allergy',
  'health.massage',
  'health.energy_drop',
  'health.vitamins',
  'health.hydration',
  'health.fresh_air',
  'health.healthy_meal',
  'health.junk_food',
  'health.meditation',
  'health.breathing',
  'health.sunlight',
  // Movement (stretching перенесена сюда из Health)
  'movement.walk',
  'movement.gym',
  'movement.run',
  'movement.yoga',
  'movement.cycling',
  'movement.home_workout',
  'movement.stretching',
  'movement.dance',
  'movement.swimming',
  'movement.hiking',
  'movement.boxing',
  'movement.sport_game',
  'movement.morning_run',
  'movement.stairs',
  'movement.team_sport',
  'movement.hiit',
  'movement.tai_chi',
  'movement.rowing',
  'movement.strength',
  'movement.climbing',
  // Rest (meditation/fishing/birdwatching убраны — дублируют Health/Hobby)
  'rest.read',
  'rest.watched_movie',
  'rest.watched_tv',
  'rest.played_games',
  'rest.listened_music',
  'rest.nap',
  'rest.relaxed',
  'rest.mobile_scroll',
  'rest.stay_in',
  'rest.hot_bath',
  'rest.quiet_morning',
  'rest.sat_outdoors',
  'rest.silence',
  'rest.audiobook',
  'rest.podcast',
  'rest.sleep_long',
  'rest.cozy',
  'rest.picnic',
  'rest.karaoke',
  // Social
  'social.friends',
  'social.family',
  'social.partner',
  'social.helped_others',
  'social.phone_call',
  'social.conflict',
  'social.date',
  'social.kids',
  'social.parents',
  'social.colleagues',
  'social.new_acquaintance',
  'social.party',
  'social.lonely',
  'social.good_communication',
  'social.volunteer',
  'social.apology',
  'social.congratulated',
  'social.hug',
  'social.heart_to_heart',
  // Hobby (fishing/birdwatching перенесены сюда из Rest, fishing_hobby убран
  // как внутрикатегорийный дубль слова «Рыбалка»)
  'hobby.drawing',
  'hobby.music_playing',
  'hobby.cooking',
  'hobby.gaming',
  'hobby.photography',
  'hobby.writing',
  'hobby.gardening',
  'hobby.puzzle',
  'hobby.board_games',
  'hobby.painting',
  'hobby.singing',
  'hobby.crafts',
  'hobby.baking',
  'hobby.fishing',
  'hobby.birdwatching',
  'hobby.knitting',
  'hobby.diy',
  'hobby.collecting',
  'hobby.escape_room',
  // Events
  'events.celebration',
  'events.holiday',
  'events.travel',
  'events.concert',
  'events.wedding',
  'events.shopping',
  'events.birthday',
  'events.anniversary',
  'events.graduation',
  'events.sport_event',
  'events.theater',
  'events.museum',
  'events.city_trip',
  'events.market',
  'events.special_meal',
  'events.fireworks',
  'events.family_gathering',
  'events.contest',
  'events.festival',
]);

export function isCoreActivity(key: string): boolean {
  return CORE_ACTIVITY_KEYS.has(key);
}

export const CORE_ACTIVITY_CATALOG: DayActivityDefinition[] = ACTIVITY_CATALOG.filter((a) =>
  CORE_ACTIVITY_KEYS.has(a.key),
);

export const DEFAULT_ACTIVITY_CATEGORY = ActivityCategory.Work;

export const ACTIVITY_ICONS: Record<string, LucideIcon> = {
  'work.worked': Briefcase,
  'work.meeting': Users,
  'work.deadline': Timer,
  'work.presentation': Presentation,
  'work.overtime': Clock,
  'work.day_off': CalendarOff,
  'work.remote': Laptop,
  'work.stressful_day': CloudLightning,
  'work.success': Trophy,
  'work.new_project': Rocket,
  'work.salary': Banknote,
  'work.business_trip': Plane,
  'work.employee_review': ClipboardList,
  'work.hired': UserCheck,
  'work.quitting': LogOut,
  'work.promotion': TrendingUp,
  'work.bad_boss': Frown,
  'work.fired': UserX,
  'work.lunch_with_colleagues': Utensils,
  'work.focus_day': Target,
  'work.remote_stress': Headphones,
  'work.team_success': UsersRound,
  'work.telework_balance': Laptop,
  'work.boring_day': Clock,
  'work.insight_work': Lightbulb,

  'study.studied': BookOpen,
  'study.exam': GraduationCap,
  'study.homework': BookCheck,
  'study.course': BookOpen,
  'study.listened_lecture': Headphones,
  'study.failed_exam': Frown,
  'study.passed_exam': CheckCircle,
  'study.learned_skill': Lightbulb,
  'study.read_textbook': BookOpen,
  'study.conference': Users,
  'study.workshop': UsersRound,
  'study.language_lesson': MessageCircle,
  'study.research': Leaf,
  'study.online_lesson': Laptop,
  'study.self_education': BookOpen,
  'study.group_project': UsersRound,

  'health.doctor_visit': Stethoscope,
  'health.therapy_session': HeartHandshake,
  'health.medication': Pill,
  'health.sick': Thermometer,
  'health.headache': Activity,
  'health.good_health': HeartPulse,
  'health.bad_sleep': Moon,
  'health.good_sleep': MoonStar,
  'health.toothache': Thermometer,
  'health.flu': Thermometer,
  'health.dental_visit': Smile,
  'health.eye_strain': Eye,
  'health.digestion': Apple,
  'health.allergy': Leaf,
  'health.massage': HeartHandshake,
  'health.gratitude_health': Heart,
  'health.energy_drop': BatteryLow,
  'health.caffeine': Coffee,
  'health.alcohol': Wine,
  'health.vitamins': Pill,
  'health.sleep_eight': BedDouble,
  'health.hydration': GlassWater,
  'health.fresh_air': Wind,

  'movement.walk': Footprints,
  'movement.gym': Dumbbell,
  'movement.run': Crosshair,
  'movement.yoga': Flower2,
  'movement.cycling': Bike,
  'movement.sport_game': Trophy,
  'movement.home_workout': Dumbbell,
  'movement.stretching': PersonStanding,
  'movement.dance': Music,
  'movement.swimming': Waves,
  'movement.hiking': Mountain,
  'movement.pilates': Flower2,
  'movement.boxing': Target,
  'movement.tennis': Crosshair,
  'movement.basketball': Trophy,
  'movement.football': Trophy,
  'movement.skateboard': PersonStanding,
  'movement.ski': Mountain,
  'movement.climbing': Mountain,
  'movement.sports_outdoor': Tent,
  'movement.morning_run': Sunrise,
  'movement.stairs': TrendingUp,
  'movement.team_sport': Users,

  'rest.read': BookOpen,
  'rest.watched_movie': Clapperboard,
  'rest.watched_tv': Tv,
  'rest.played_games': Gamepad2,
  'rest.listened_music': Music,
  'rest.nap': BedDouble,
  'rest.relaxed': Coffee,
  'rest.mobile_scroll': Smartphone,
  'rest.walked_leisure': Footprints,
  'rest.stay_in': Home,
  'rest.hot_bath': Bath,
  'rest.meditation': Flower2,
  'rest.quiet_morning': Sunrise,
  'rest.social_media': Smartphone,
  'rest.sat_outdoors': Tent,
  'rest.tea_ceremony': Coffee,
  'rest.silence': Moon,

  'social.friends': Users,
  'social.family': UsersRound,
  'social.partner': Heart,
  'social.helped_others': HandHeart,
  'social.phone_call': Phone,
  'social.conflict': Frown,
  'social.date': HeartHandshake,
  'social.kids': Baby,
  'social.parents': UsersRound,
  'social.colleagues': Users,
  'social.new_acquaintance': UserPlus,
  'social.reunion': UsersRound,
  'social.neighbors': Home,
  'social.party': PartyPopper,
  'social.networking': Share2,
  'social.support_group': HeartHandshake,
  'social.lonely': Frown,
  'social.good_communication': MessageCircle,
  'social.cooked_for_others': ChefHat,
  'social.thanks_text': MessageSquareHeart,
  'social.visit': Home,

  'hobby.drawing': Pen,
  'hobby.music_playing': Music,
  'hobby.cooking': ChefHat,
  'hobby.gaming': Gamepad2,
  'hobby.photography': Camera,
  'hobby.writing': PenLine,
  'hobby.diy': Hammer,
  'hobby.knitting': Scissors,
  'hobby.gardening': Sprout,
  'hobby.puzzle': Puzzle,
  'hobby.board_games': Puzzle,
  'hobby.collecting': Archive,
  'hobby.pottery': Brush,
  'hobby.painting': Brush,
  'hobby.singing': Mic,
  'hobby.rebuild_car': Car,
  'hobby.build_model': Hammer,
  'hobby.crafts': Scissors,
  'hobby.baking': Croissant,
  'hobby.fishing': Waves,
  'hobby.birdwatching': Bird,

  'events.celebration': PartyPopper,
  'events.holiday': Sun,
  'events.travel': Plane,
  'events.concert': Music,
  'events.wedding': Heart,
  'events.shopping': ShoppingBag,
  'events.birthday': Cake,
  'events.anniversary': Gift,
  'events.graduation': GraduationCap,
  'events.sport_event': Trophy,
  'events.theater': Ticket,
  'events.museum': Landmark,
  'events.city_trip': MapPin,
  'events.market': Store,
  'events.religious_day': Church,
  'events.special_meal': Utensils,
  'events.city_festival': PartyPopper,
  'events.first_snow': Snowflake,
  'events.moved': Truck,

  'wellbeing.stress': CloudLightning,
  'wellbeing.anxiety': Wind,
  'wellbeing.good_mood': Smile,
  'wellbeing.low_mood': Frown,
  'wellbeing.grateful': Heart,
  'wellbeing.peaceful': Flower2,
  'wellbeing.overwhelmed': CloudRainWind,
  'wellbeing.energetic': Zap,
  'wellbeing.tired': BatteryLow,
  'wellbeing.rainy_day': CloudDrizzle,
  'wellbeing.sunny_day': Sun,
  'wellbeing.motivated': Rocket,
  'wellbeing.hopeful': Sunrise,
  'wellbeing.sad': Frown,
  'wellbeing.angry': Angry,
  'wellbeing.irritated': CloudLightning,
  'wellbeing.calm': Moon,
  'wellbeing.stress_relief': Wind,
  'wellbeing.breakthrough': Lightbulb,
  'wellbeing.self_care': HeartHandshake,
  'wellbeing.rush': Timer,
  'wellbeing.satisfied': CheckCircle,
  'wellbeing.lonely_day': Frown,
  'wellbeing.wild_day': Zap,
  'wellbeing.routine_day': RotateCcw,
  'wellbeing.fresh_start': Sparkles,
  'wellbeing.slept_early': MoonStar,
  'wellbeing.mood_swing': ArrowLeftRight,
  'wellbeing.confidence': ShieldCheck,
  'work.sprint': Rocket,
  'work.standup': Users,
  'work.retro': MessageCircle,
  'work.mentoring': UserCheck,
  'work.code_review': Eye,
  'work.new_tool': Wrench,
  'work.planning': CalendarCheck,
  'work.deadline_met': Trophy,
  'work.missed_deadline': Frown,
  'work.conflict': CloudRain,
  'work.praise': ThumbsUp,
  'work.crunch': Clock3,
  'work.slow_day': Clock,
  'work.home_office': Home,
  'work.remote_call': Phone,
  'work.internship': GraduationCap,
  'work.freelance': Banknote,
  'work.side_project': Lightbulb,
  'work.team_building': Users,
  'work.boring_task': Frown,
  'study.flashcards': Layers,
  'study.notes': PenLine,
  'study.webinar': Monitor,
  'study.online_course': Laptop,
  'study.mentor': UserCheck,
  'study.practice': Wrench,
  'study.project': Rocket,
  'study.group_work': Users,
  'study.revision': RotateCcw,
  'study.mistake': Frown,
  'study.success_study': Trophy,
  'study.motivation': Zap,
  'study.burnout': BatteryLow,
  'study.schedule': CalendarCheck,
  'study.exam_prep': Timer,
  'study.deadline_study': Clock3,
  'study.discussion': MessageCircle,
  'study.focus_study': Target,
  'study.reading': BookOpen,
  'study.digital_notes': Laptop,
  'health.checkup': Stethoscope,
  'health.blood_test': TestTube,
  'health.physio': Activity,
  'health.osteopath': HandHeart,
  'health.vaccine': Syringe,
  'health.acupuncture': Zap,
  'health.eye_test': Eye,
  'health.healthy_meal': Salad,
  'health.junk_food': Cookie,
  'health.less_sugar': Sparkles,
  'health.stretching': PersonStanding,
  'health.breathing': Wind,
  'health.cold_shower': Snowflake,
  'health.sauna': Flame,
  'health.sunlight': Sun,
  'health.meditation': Flower2,
  'health.sleep_disrupted': Moon,
  'health.sleep_late': MoonStar,
  'health.phone_before_sleep': Smartphone,
  'health.regular_meal': Utensils,
  'movement.walk_park': Trees,
  'movement.sprints': Zap,
  'movement.pingpong': Target,
  'movement.badminton': Crosshair,
  'movement.volleyball': Trophy,
  'movement.hockey': Snowflake,
  'movement.skating': Footprints,
  'movement.rollers': PersonStanding,
  'movement.trampoline': Activity,
  'movement.calisthenics': Dumbbell,
  'movement.hiit': Flame,
  'movement.crossfit': Zap,
  'movement.tai_chi': Flower2,
  'movement.horse': PawPrint,
  'movement.rowing': Waves,
  'movement.rock_climb': Mountain,
  'movement.dance_class': Music,
  'movement.gym_light': BatteryLow,
  'movement.workout_outside': Tent,
  'movement.strength': Dumbbell,
  'rest.audiobook': Headphones,
  'rest.podcast': Mic,
  'rest.sleep_long': BedDouble,
  'rest.cozy': Home,
  'rest.stargazing': Sparkles,
  'rest.picnic': Tent,
  'rest.camping': Tent,
  'rest.chess': Castle,
  'rest.cards': Puzzle,
  'rest.karaoke': Mic,
  'rest.sauna_rest': Flame,
  'rest.lazy_day': Frown,
  'rest.sunbathing': Sun,
  'rest.fishing': Waves,
  'rest.birdwatching': Bird,
  'rest.balcony': Wind,
  'rest.library': Landmark,
  'rest.quiet_cafe': Coffee,
  'rest.painting_rest': Palette,
  'rest.dance_rest': Music,
  'social.group_chat': MessageCircle,
  'social.video_call': Video,
  'social.online_game': Gamepad2,
  'social.sibling': Users,
  'social.grandparents': UsersRound,
  'social.pet': PawPrint,
  'social.volunteer': HandHeart,
  'social.mentor_social': UserCheck,
  'social.boundary': ShieldCheck,
  'social.apology': HeartHandshake,
  'social.gift_social': Gift,
  'social.congratulated': Sparkles,
  'social.work_event': PartyPopper,
  'social.community': Users,
  'social.help_stranger': HandHeart,
  'social.meetup': UsersRound,
  'social.photo_call': Video,
  'social.voice': Mic,
  'social.hug': Heart,
  'social.heart_to_heart': MessageCircle,
  'hobby.embroidery': Scissors,
  'hobby.beading': Sparkles,
  'hobby.macrame': Scissors,
  'hobby.resin': Droplet,
  'hobby.soap': Droplet,
  'hobby.candles': Flame,
  'hobby.origami': FoldHorizontal,
  'hobby.calligraphy': PenTool,
  'hobby.woodwork': Hammer,
  'hobby.metalwork': Wrench,
  'hobby.print3d': Boxes,
  'hobby.robotics': Cog,
  'hobby.drone': Plane,
  'hobby.simulators': Gamepad2,
  'hobby.escape_room': Puzzle,
  'hobby.chess_hobby': Castle,
  'hobby.stamps': Archive,
  'hobby.kayak': Waves,
  'hobby.mushrooms': Sprout,
  'hobby.fishing_hobby': Waves,
  'events.exhibition': Landmark,
  'events.premiere': Clapperboard,
  'events.opera': Music,
  'events.ballet': Music,
  'events.festival': PartyPopper,
  'events.parade': Flag,
  'events.carnival': Sparkles,
  'events.fireworks': Sparkles,
  'events.book_fair': BookOpen,
  'events.food_festival': Utensils,
  'events.gala': Wine,
  'events.retreat': Mountain,
  'events.family_gathering': UsersRound,
  'events.visit_relatives': Home,
  'events.open_air': Music,
  'events.standup_comedy': Mic,
  'events.kids_party': Baby,
  'events.charity_event': Heart,
  'events.contest': Trophy,
  'events.holiday_home': PartyPopper,
  'wellbeing.breathing_well': Wind,
  'wellbeing.journaling': PenLine,
  'wellbeing.affirmations': Sparkles,
  'wellbeing.digital_detox': Smartphone,
  'wellbeing.nature': Trees,
  'wellbeing.cold_shower_well': Snowflake,
  'wellbeing.sunlight_well': Sun,
  'wellbeing.gratitude_well': Heart,
  'wellbeing.positive': Smile,
  'wellbeing.boundaries_well': ShieldCheck,
  'wellbeing.self_care_extra': HeartHandshake,
  'wellbeing.routine': CalendarCheck,
  'wellbeing.music_well': Music,
  'wellbeing.art_therapy': Palette,
  'wellbeing.reading_well': BookOpen,
  'wellbeing.mindful_walk': Footprints,
  'wellbeing.social_joy': Users,
  'wellbeing.cried': Frown,
  'wellbeing.let_off_steam': Zap,
  'wellbeing.smiled': Smile,
};
