import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Angry,
  Apple,
  Archive,
  ArrowLeftRight,
  Baby,
  Banknote,
  Bath,
  BatteryLow,
  BedDouble,
  Bike,
  Bird,
  BookCheck,
  BookOpen,
  Briefcase,
  Brush,
  Cake,
  CalendarOff,
  Camera,
  Car,
  CheckCircle,
  ChefHat,
  Church,
  Clapperboard,
  ClipboardList,
  Clock,
  CloudDrizzle,
  CloudLightning,
  CloudRainWind,
  Coffee,
  Crosshair,
  Croissant,
  Dumbbell,
  Eye,
  Flower2,
  Frown,
  Footprints,
  Gamepad2,
  Gift,
  GlassWater,
  GraduationCap,
  Hammer,
  HandHeart,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  Home,
  Laptop,
  Landmark,
  Leaf,
  Lightbulb,
  LogOut,
  MapPin,
  MessageCircle,
  MessageSquareHeart,
  Mic,
  Moon,
  MoonStar,
  Mountain,
  Music,
  PartyPopper,
  Pen,
  PenLine,
  PersonStanding,
  Phone,
  Pill,
  Plane,
  Presentation,
  Puzzle,
  Rocket,
  RotateCcw,
  Scissors,
  Share2,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Smile,
  Snowflake,
  Sparkles,
  Sprout,
  Stethoscope,
  Store,
  Sun,
  Sunrise,
  Target,
  Tent,
  Thermometer,
  Ticket,
  Timer,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  UserCheck,
  UserPlus,
  Users,
  UserX,
  UsersRound,
  Utensils,
  Waves,
  Wind,
  Wine,
  Zap,
} from "lucide-react";

export enum ActivityCategory {
  Work = "work",
  Study = "study",
  Health = "health",
  Movement = "movement",
  Rest = "rest",
  Social = "social",
  Hobby = "hobby",
  Events = "events",
  Wellbeing = "wellbeing",
}

export const CATEGORY_ICONS: Record<ActivityCategory, LucideIcon> = {
  [ActivityCategory.Work]: Briefcase,
  [ActivityCategory.Study]: GraduationCap,
  [ActivityCategory.Health]: HeartPulse,
  [ActivityCategory.Movement]: Dumbbell,
  [ActivityCategory.Rest]: Moon,
  [ActivityCategory.Social]: Users,
  [ActivityCategory.Hobby]: Music,
  [ActivityCategory.Events]: PartyPopper,
  [ActivityCategory.Wellbeing]: Sparkles,
};

export interface DayActivityDefinition {
  key: string;
  category: ActivityCategory;
  labelKey: string;
}

export const ACTIVITY_CATEGORY_ORDER: ActivityCategory[] = [
  ActivityCategory.Work,
  ActivityCategory.Study,
  ActivityCategory.Health,
  ActivityCategory.Movement,
  ActivityCategory.Rest,
  ActivityCategory.Social,
  ActivityCategory.Hobby,
  ActivityCategory.Events,
  ActivityCategory.Wellbeing,
];

const CAT: Record<ActivityCategory, ActivityCategory> = {
  work: ActivityCategory.Work,
  study: ActivityCategory.Study,
  health: ActivityCategory.Health,
  movement: ActivityCategory.Movement,
  rest: ActivityCategory.Rest,
  social: ActivityCategory.Social,
  hobby: ActivityCategory.Hobby,
  events: ActivityCategory.Events,
  wellbeing: ActivityCategory.Wellbeing,
};

function def(categoryKey: ActivityCategory, key: string): DayActivityDefinition {
  return {
    key: `${categoryKey}.${key}`,
    category: CAT[categoryKey],
    labelKey: `dayActivities.activities.${categoryKey}_${key}`,
  };
}

export const ACTIVITY_CATALOG: DayActivityDefinition[] = [
  def(ActivityCategory.Work, "worked"),
  def(ActivityCategory.Work, "meeting"),
  def(ActivityCategory.Work, "deadline"),
  def(ActivityCategory.Work, "presentation"),
  def(ActivityCategory.Work, "overtime"),
  def(ActivityCategory.Work, "day_off"),
  def(ActivityCategory.Work, "remote"),
  def(ActivityCategory.Work, "stressful_day"),
  def(ActivityCategory.Work, "success"),
  def(ActivityCategory.Work, "new_project"),
  def(ActivityCategory.Work, "salary"),
  def(ActivityCategory.Work, "business_trip"),
  def(ActivityCategory.Work, "employee_review"),
  def(ActivityCategory.Work, "hired"),
  def(ActivityCategory.Work, "quitting"),
  def(ActivityCategory.Work, "promotion"),
  def(ActivityCategory.Work, "bad_boss"),
  def(ActivityCategory.Work, "fired"),
  def(ActivityCategory.Work, "lunch_with_colleagues"),
  def(ActivityCategory.Work, "focus_day"),
  def(ActivityCategory.Work, "remote_stress"),
  def(ActivityCategory.Work, "team_success"),
  def(ActivityCategory.Study, "studied"),
  def(ActivityCategory.Study, "exam"),
  def(ActivityCategory.Study, "homework"),
  def(ActivityCategory.Study, "course"),
  def(ActivityCategory.Study, "listened_lecture"),
  def(ActivityCategory.Study, "failed_exam"),
  def(ActivityCategory.Study, "passed_exam"),
  def(ActivityCategory.Study, "learned_skill"),
  def(ActivityCategory.Study, "read_textbook"),
  def(ActivityCategory.Study, "conference"),
  def(ActivityCategory.Study, "workshop"),
  def(ActivityCategory.Study, "language_lesson"),
  def(ActivityCategory.Study, "research"),
  def(ActivityCategory.Health, "doctor_visit"),
  def(ActivityCategory.Health, "therapy_session"),
  def(ActivityCategory.Health, "medication"),
  def(ActivityCategory.Health, "sick"),
  def(ActivityCategory.Health, "headache"),
  def(ActivityCategory.Health, "good_health"),
  def(ActivityCategory.Health, "bad_sleep"),
  def(ActivityCategory.Health, "good_sleep"),
  def(ActivityCategory.Health, "toothache"),
  def(ActivityCategory.Health, "flu"),
  def(ActivityCategory.Health, "dental_visit"),
  def(ActivityCategory.Health, "eye_strain"),
  def(ActivityCategory.Health, "digestion"),
  def(ActivityCategory.Health, "allergy"),
  def(ActivityCategory.Health, "massage"),
  def(ActivityCategory.Health, "gratitude_health"),
  def(ActivityCategory.Health, "energy_drop"),
  def(ActivityCategory.Health, "caffeine"),
  def(ActivityCategory.Health, "alcohol"),
  def(ActivityCategory.Movement, "walk"),
  def(ActivityCategory.Movement, "gym"),
  def(ActivityCategory.Movement, "run"),
  def(ActivityCategory.Movement, "yoga"),
  def(ActivityCategory.Movement, "cycling"),
  def(ActivityCategory.Movement, "sport_game"),
  def(ActivityCategory.Movement, "home_workout"),
  def(ActivityCategory.Movement, "stretching"),
  def(ActivityCategory.Movement, "dance"),
  def(ActivityCategory.Movement, "swimming"),
  def(ActivityCategory.Movement, "hiking"),
  def(ActivityCategory.Movement, "pilates"),
  def(ActivityCategory.Movement, "boxing"),
  def(ActivityCategory.Movement, "tennis"),
  def(ActivityCategory.Movement, "basketball"),
  def(ActivityCategory.Movement, "football"),
  def(ActivityCategory.Movement, "skateboard"),
  def(ActivityCategory.Movement, "ski"),
  def(ActivityCategory.Movement, "climbing"),
  def(ActivityCategory.Movement, "sports_outdoor"),
  def(ActivityCategory.Rest, "read"),
  def(ActivityCategory.Rest, "watched_movie"),
  def(ActivityCategory.Rest, "watched_tv"),
  def(ActivityCategory.Rest, "played_games"),
  def(ActivityCategory.Rest, "listened_music"),
  def(ActivityCategory.Rest, "nap"),
  def(ActivityCategory.Rest, "relaxed"),
  def(ActivityCategory.Rest, "mobile_scroll"),
  def(ActivityCategory.Rest, "walked_leisure"),
  def(ActivityCategory.Rest, "stay_in"),
  def(ActivityCategory.Rest, "hot_bath"),
  def(ActivityCategory.Rest, "meditation"),
  def(ActivityCategory.Rest, "quiet_morning"),
  def(ActivityCategory.Rest, "social_media"),
  def(ActivityCategory.Social, "friends"),
  def(ActivityCategory.Social, "family"),
  def(ActivityCategory.Social, "partner"),
  def(ActivityCategory.Social, "helped_others"),
  def(ActivityCategory.Social, "phone_call"),
  def(ActivityCategory.Social, "conflict"),
  def(ActivityCategory.Social, "date"),
  def(ActivityCategory.Social, "kids"),
  def(ActivityCategory.Social, "parents"),
  def(ActivityCategory.Social, "colleagues"),
  def(ActivityCategory.Social, "new_acquaintance"),
  def(ActivityCategory.Social, "reunion"),
  def(ActivityCategory.Social, "neighbors"),
  def(ActivityCategory.Social, "party"),
  def(ActivityCategory.Social, "networking"),
  def(ActivityCategory.Social, "support_group"),
  def(ActivityCategory.Social, "lonely"),
  def(ActivityCategory.Social, "good_communication"),
  def(ActivityCategory.Hobby, "drawing"),
  def(ActivityCategory.Hobby, "music_playing"),
  def(ActivityCategory.Hobby, "cooking"),
  def(ActivityCategory.Hobby, "gaming"),
  def(ActivityCategory.Hobby, "photography"),
  def(ActivityCategory.Hobby, "writing"),
  def(ActivityCategory.Hobby, "diy"),
  def(ActivityCategory.Hobby, "knitting"),
  def(ActivityCategory.Hobby, "gardening"),
  def(ActivityCategory.Hobby, "puzzle"),
  def(ActivityCategory.Hobby, "board_games"),
  def(ActivityCategory.Hobby, "collecting"),
  def(ActivityCategory.Hobby, "pottery"),
  def(ActivityCategory.Hobby, "painting"),
  def(ActivityCategory.Hobby, "singing"),
  def(ActivityCategory.Hobby, "rebuild_car"),
  def(ActivityCategory.Hobby, "build_model"),
  def(ActivityCategory.Hobby, "crafts"),
  def(ActivityCategory.Events, "celebration"),
  def(ActivityCategory.Events, "holiday"),
  def(ActivityCategory.Events, "travel"),
  def(ActivityCategory.Events, "concert"),
  def(ActivityCategory.Events, "wedding"),
  def(ActivityCategory.Events, "shopping"),
  def(ActivityCategory.Events, "birthday"),
  def(ActivityCategory.Events, "anniversary"),
  def(ActivityCategory.Events, "graduation"),
  def(ActivityCategory.Events, "sport_event"),
  def(ActivityCategory.Events, "theater"),
  def(ActivityCategory.Events, "museum"),
  def(ActivityCategory.Events, "city_trip"),
  def(ActivityCategory.Events, "market"),
  def(ActivityCategory.Events, "religious_day"),
  def(ActivityCategory.Events, "special_meal"),
  def(ActivityCategory.Wellbeing, "stress"),
  def(ActivityCategory.Wellbeing, "anxiety"),
  def(ActivityCategory.Wellbeing, "good_mood"),
  def(ActivityCategory.Wellbeing, "low_mood"),
  def(ActivityCategory.Wellbeing, "grateful"),
  def(ActivityCategory.Wellbeing, "peaceful"),
  def(ActivityCategory.Wellbeing, "overwhelmed"),
  def(ActivityCategory.Wellbeing, "energetic"),
  def(ActivityCategory.Wellbeing, "tired"),
  def(ActivityCategory.Wellbeing, "rainy_day"),
  def(ActivityCategory.Wellbeing, "sunny_day"),
  def(ActivityCategory.Wellbeing, "motivated"),
  def(ActivityCategory.Wellbeing, "hopeful"),
  def(ActivityCategory.Wellbeing, "sad"),
  def(ActivityCategory.Wellbeing, "angry"),
  def(ActivityCategory.Wellbeing, "irritated"),
  def(ActivityCategory.Wellbeing, "calm"),
  def(ActivityCategory.Wellbeing, "stress_relief"),
  def(ActivityCategory.Wellbeing, "breakthrough"),
  def(ActivityCategory.Wellbeing, "self_care"),
  def(ActivityCategory.Wellbeing, "rush"),
  def(ActivityCategory.Wellbeing, "satisfied"),
  def(ActivityCategory.Wellbeing, "lonely_day"),
  def(ActivityCategory.Wellbeing, "wild_day"),
  def(ActivityCategory.Wellbeing, "routine_day"),
  def(ActivityCategory.Work, "telework_balance"),
  def(ActivityCategory.Work, "boring_day"),
  def(ActivityCategory.Work, "insight_work"),
  def(ActivityCategory.Study, "online_lesson"),
  def(ActivityCategory.Study, "self_education"),
  def(ActivityCategory.Study, "group_project"),
  def(ActivityCategory.Health, "vitamins"),
  def(ActivityCategory.Health, "sleep_eight"),
  def(ActivityCategory.Health, "hydration"),
  def(ActivityCategory.Health, "fresh_air"),
  def(ActivityCategory.Movement, "morning_run"),
  def(ActivityCategory.Movement, "stairs"),
  def(ActivityCategory.Movement, "team_sport"),
  def(ActivityCategory.Rest, "sat_outdoors"),
  def(ActivityCategory.Rest, "tea_ceremony"),
  def(ActivityCategory.Rest, "silence"),
  def(ActivityCategory.Social, "cooked_for_others"),
  def(ActivityCategory.Social, "thanks_text"),
  def(ActivityCategory.Social, "visit"),
  def(ActivityCategory.Hobby, "baking"),
  def(ActivityCategory.Hobby, "fishing"),
  def(ActivityCategory.Hobby, "birdwatching"),
  def(ActivityCategory.Events, "city_festival"),
  def(ActivityCategory.Events, "first_snow"),
  def(ActivityCategory.Events, "moved"),
  def(ActivityCategory.Wellbeing, "fresh_start"),
  def(ActivityCategory.Wellbeing, "slept_early"),
  def(ActivityCategory.Wellbeing, "mood_swing"),
  def(ActivityCategory.Wellbeing, "confidence"),
];

export const DEFAULT_ACTIVITY_CATEGORY = ActivityCategory.Wellbeing;

export const ACTIVITY_ICONS: Record<string, LucideIcon> = {
  "work.worked": Briefcase,
  "work.meeting": Users,
  "work.deadline": Timer,
  "work.presentation": Presentation,
  "work.overtime": Clock,
  "work.day_off": CalendarOff,
  "work.remote": Laptop,
  "work.stressful_day": CloudLightning,
  "work.success": Trophy,
  "work.new_project": Rocket,
  "work.salary": Banknote,
  "work.business_trip": Plane,
  "work.employee_review": ClipboardList,
  "work.hired": UserCheck,
  "work.quitting": LogOut,
  "work.promotion": TrendingUp,
  "work.bad_boss": Frown,
  "work.fired": UserX,
  "work.lunch_with_colleagues": Utensils,
  "work.focus_day": Target,
  "work.remote_stress": Headphones,
  "work.team_success": UsersRound,
  "work.telework_balance": Laptop,
  "work.boring_day": Clock,
  "work.insight_work": Lightbulb,

  "study.studied": BookOpen,
  "study.exam": GraduationCap,
  "study.homework": BookCheck,
  "study.course": BookOpen,
  "study.listened_lecture": Headphones,
  "study.failed_exam": Frown,
  "study.passed_exam": CheckCircle,
  "study.learned_skill": Lightbulb,
  "study.read_textbook": BookOpen,
  "study.conference": Users,
  "study.workshop": UsersRound,
  "study.language_lesson": MessageCircle,
  "study.research": Leaf,
  "study.online_lesson": Laptop,
  "study.self_education": BookOpen,
  "study.group_project": UsersRound,

  "health.doctor_visit": Stethoscope,
  "health.therapy_session": HeartHandshake,
  "health.medication": Pill,
  "health.sick": Thermometer,
  "health.headache": Activity,
  "health.good_health": HeartPulse,
  "health.bad_sleep": Moon,
  "health.good_sleep": MoonStar,
  "health.toothache": Thermometer,
  "health.flu": Thermometer,
  "health.dental_visit": Smile,
  "health.eye_strain": Eye,
  "health.digestion": Apple,
  "health.allergy": Leaf,
  "health.massage": HeartHandshake,
  "health.gratitude_health": Heart,
  "health.energy_drop": BatteryLow,
  "health.caffeine": Coffee,
  "health.alcohol": Wine,
  "health.vitamins": Pill,
  "health.sleep_eight": BedDouble,
  "health.hydration": GlassWater,
  "health.fresh_air": Wind,

  "movement.walk": Footprints,
  "movement.gym": Dumbbell,
  "movement.run": Crosshair,
  "movement.yoga": Flower2,
  "movement.cycling": Bike,
  "movement.sport_game": Trophy,
  "movement.home_workout": Dumbbell,
  "movement.stretching": PersonStanding,
  "movement.dance": Music,
  "movement.swimming": Waves,
  "movement.hiking": Mountain,
  "movement.pilates": Flower2,
  "movement.boxing": Target,
  "movement.tennis": Crosshair,
  "movement.basketball": Trophy,
  "movement.football": Trophy,
  "movement.skateboard": PersonStanding,
  "movement.ski": Mountain,
  "movement.climbing": Mountain,
  "movement.sports_outdoor": Tent,
  "movement.morning_run": Sunrise,
  "movement.stairs": TrendingUp,
  "movement.team_sport": Users,

  "rest.read": BookOpen,
  "rest.watched_movie": Clapperboard,
  "rest.watched_tv": Tv,
  "rest.played_games": Gamepad2,
  "rest.listened_music": Music,
  "rest.nap": BedDouble,
  "rest.relaxed": Coffee,
  "rest.mobile_scroll": Smartphone,
  "rest.walked_leisure": Footprints,
  "rest.stay_in": Home,
  "rest.hot_bath": Bath,
  "rest.meditation": Flower2,
  "rest.quiet_morning": Sunrise,
  "rest.social_media": Smartphone,
  "rest.sat_outdoors": Tent,
  "rest.tea_ceremony": Coffee,
  "rest.silence": Moon,

  "social.friends": Users,
  "social.family": UsersRound,
  "social.partner": Heart,
  "social.helped_others": HandHeart,
  "social.phone_call": Phone,
  "social.conflict": Frown,
  "social.date": HeartHandshake,
  "social.kids": Baby,
  "social.parents": UsersRound,
  "social.colleagues": Users,
  "social.new_acquaintance": UserPlus,
  "social.reunion": UsersRound,
  "social.neighbors": Home,
  "social.party": PartyPopper,
  "social.networking": Share2,
  "social.support_group": HeartHandshake,
  "social.lonely": Frown,
  "social.good_communication": MessageCircle,
  "social.cooked_for_others": ChefHat,
  "social.thanks_text": MessageSquareHeart,
  "social.visit": Home,

  "hobby.drawing": Pen,
  "hobby.music_playing": Music,
  "hobby.cooking": ChefHat,
  "hobby.gaming": Gamepad2,
  "hobby.photography": Camera,
  "hobby.writing": PenLine,
  "hobby.diy": Hammer,
  "hobby.knitting": Scissors,
  "hobby.gardening": Sprout,
  "hobby.puzzle": Puzzle,
  "hobby.board_games": Puzzle,
  "hobby.collecting": Archive,
  "hobby.pottery": Brush,
  "hobby.painting": Brush,
  "hobby.singing": Mic,
  "hobby.rebuild_car": Car,
  "hobby.build_model": Hammer,
  "hobby.crafts": Scissors,
  "hobby.baking": Croissant,
  "hobby.fishing": Waves,
  "hobby.birdwatching": Bird,

  "events.celebration": PartyPopper,
  "events.holiday": Sun,
  "events.travel": Plane,
  "events.concert": Music,
  "events.wedding": Heart,
  "events.shopping": ShoppingBag,
  "events.birthday": Cake,
  "events.anniversary": Gift,
  "events.graduation": GraduationCap,
  "events.sport_event": Trophy,
  "events.theater": Ticket,
  "events.museum": Landmark,
  "events.city_trip": MapPin,
  "events.market": Store,
  "events.religious_day": Church,
  "events.special_meal": Utensils,
  "events.city_festival": PartyPopper,
  "events.first_snow": Snowflake,
  "events.moved": Truck,

  "wellbeing.stress": CloudLightning,
  "wellbeing.anxiety": Wind,
  "wellbeing.good_mood": Smile,
  "wellbeing.low_mood": Frown,
  "wellbeing.grateful": Heart,
  "wellbeing.peaceful": Flower2,
  "wellbeing.overwhelmed": CloudRainWind,
  "wellbeing.energetic": Zap,
  "wellbeing.tired": BatteryLow,
  "wellbeing.rainy_day": CloudDrizzle,
  "wellbeing.sunny_day": Sun,
  "wellbeing.motivated": Rocket,
  "wellbeing.hopeful": Sunrise,
  "wellbeing.sad": Frown,
  "wellbeing.angry": Angry,
  "wellbeing.irritated": CloudLightning,
  "wellbeing.calm": Moon,
  "wellbeing.stress_relief": Wind,
  "wellbeing.breakthrough": Lightbulb,
  "wellbeing.self_care": HeartHandshake,
  "wellbeing.rush": Timer,
  "wellbeing.satisfied": CheckCircle,
  "wellbeing.lonely_day": Frown,
  "wellbeing.wild_day": Zap,
  "wellbeing.routine_day": RotateCcw,
  "wellbeing.fresh_start": Sparkles,
  "wellbeing.slept_early": MoonStar,
  "wellbeing.mood_swing": ArrowLeftRight,
  "wellbeing.confidence": ShieldCheck,
};
